### ISSUE TITLE
Migrer Inspire vers inspire.beta.gouv.fr

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#102]
Ou déjà en prod sur son nom de domaine définitif `inspire.data.gouv.fr` ?

**Comment by jdesboeufs** [comment]
On peut considérer qu'on est en production sur `inspire.data.gouv.fr`.
Mais peut-être que je peux migrer `inspire-next.sgmap.fr` vers `inspire.beta.gouv.fr`. Moi ça me va bien.

**Comment by MattiSG** [comment]
:+1:

**Comment by jdesboeufs** [comment]
Il n'y a pas de version next planifiée pour le moment, donc on peut fermer je pense.

**Comment by MattiSG** [comment]
Ok !
