### ISSUE TITLE
Migrer Mes Aides vers mes-aides.beta.gouv.fr

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#105]
Seulement pour les branches de staging.

**Comment by jdesboeufs** [comment]
Alors ? :)
Je peux le faire si besoin, ça doit prendre 2 minutes.

**Comment by MattiSG** [comment]
Faut vérifier quel est le nécessaire à faire sur le [générateur](https://github.com/sgmap/mes-aides-ui/blob/master/deploy.sh#L70-L101) et màj les éléments de config pour http://paris.mes-aides.sgmap.fr et http://aah.mes-aides.sgmap.fr

**Comment by MattiSG** [comment]
@fpagnoux peux-tu prendre ?

**Comment by fpagnoux** [comment]
OK, je prends.

**Comment by fpagnoux** [comment]
Testé pour http://unify-deployment.mes-aides.beta.gouv.fr/, je migre le reste rapidement.
