### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by ppezziardi** [sgmap/beta.gouv.fr#107]
Equipe & Recrutement -> page équipe avec photo et 180 signes par membre, et lien pour postuler en tant que dev, ou en tant que PO avec une idée.
FAQ
Contact -> avant de nous contacter, merci de parcourir la FAQ, et sinon contact (arobas) beta.gouv.fr
SGMAP -> lien vers modernisation.gouv.fr
Mentions légales -> page éditeur type mes-aides.

**Comment by MattiSG** [comment]
Le footer est bien plus éditable maintenant (`_includes/footer.md`).

Il faut créer la page équipe (#114). On peut créer FAQ et Mentions Légales, mais je n'ai pas encore de contenu à mettre, n'hésite pas à ouvrir une PR.
