### ISSUE TITLE
a-propos.md est une page orpheline

### ISSUE THREAD

**Issue by jilljenn** [sgmap/beta.gouv.fr#109]
Pourquoi ?
https://beta.gouv.fr/a-propos.html

**Comment by MattiSG** [comment]
Merci @jilljenn pour cette remarque !  :)

Tout simplement parce que l'adéquation entre ce texte et les descriptions actuelles de l'approche Startup d'État sur la page d'accueil, qui ont été écrites plus tard, n'était plus certaine quand on a déployé la version actuelle. On va remettre un lien vers cette page détaillée, peut-être en retravaillant le contenu, dès que l'éditorial de la page d'accueil aura été étoffé (cf. #111).
