### ISSUE TITLE
Le lien vers le site "Le Taxi" sur la page startup correspondante ne fonctionne pas

### ISSUE THREAD

**Issue by ThierryAbalea** [sgmap/beta.gouv.fr#155]
Le lien vers le site "Le Taxi" contenu dans la page https://beta.gouv.fr/startup/taxi.html ne fonctionne pas. La page pointe vers l'URL https://le.taxi au lieu de http://le.taxi. Le site "Le Taxi" ne supporte visiblement pas HTTPS. L'origine du problème vient visiblement du commit suivant: https://github.com/sgmap/beta.gouv.fr/commit/d6bb075d004c2258aa4b81db5209a57937d1040c
Le template des pages startup suppose ainsi que tous les sites supportent HTTPS

**Comment by odtvince** [comment]
Corrigé coté le.taxi, au moins pour les navigateurs récents : https://le.taxi/ 
Merci pour l'alerte. :)

**Comment by MattiSG** [comment]
Merci beaucoup @ThierryAbalea pour ce rapport détaillé !

@odtvince qu'entends-tu par « pour les navigateurs récents » ? Quelle proportion d'usagers ne pourront pas accéder à le.taxi en HTTPS ?

**Comment by odtvince** [comment]
MSIE sur Windows XP, ou le navigateur par défaut sur Android 2.3.x, par exemple, ne supportent pas SNI.
Cela ne devrait pas représenter une part significative des usagers.

**Comment by MattiSG** [comment]
[Effectivement](http://caniuse.com/#feat=sni).

Merci à tous !
