### ISSUE TITLE
Épurer la page d'accueil

### ISSUE THREAD

**Issue by Flightan** [sgmap/beta.gouv.fr#196]
As discussed with @HelaG 

WDYT ?

![proposition-redesign](https://cloud.githubusercontent.com/assets/1475946/15434633/157922e0-1eb8-11e6-81c7-688c1e5195f0.png)

**Comment by Morendil** [comment]
En mode perfection game, 6/10. Ce que j'aime bien: la sobriété, l'arbitrage en faveur des screenshots qui ne partagent plus la vedette avec la photo de l'open space de Sully.

Pour avoir 10/10:

Je mettrais le tableau de bord au-dessus du narratif des 4 phases peut-être: le visuel d'abord, le texte ensuite. Je trouverais des couleurs moins tristounes que le camaïeu de gris pour le tableau de bord.

Je chercherais un endroit pour les textes descriptifs détaillés des 4 phases qui se retrouvent orphelins, les pauvres.

Il manque aussi un menu pour donner accès au reste: les événements/blogs, la page équipe...

"Explorez 21 autres Startups d'Etat" => "Découvrez toutes les startups"

**Comment by MattiSG** [comment]
:+1:

Le over-the-fold est super.

Deux points :

- Le dégradé de gris diminue trop l'importance du processus, car les nuances de gris sont utilisées pour les fonds. Préférer des couleurs.
- La flèche triangulaire vers la droite en regard de la capture d'écran est ambiguë : s'agit-il d'afficher un autre exemple ou d'entrer dans Mes Aides ?

**Comment by laem** [comment]
:+1: 
J'aime bien la Marianne qui respire enfin, et d'avantage de simplicité. 
J'aurais mis une autre couleur que le jaune en bas (par exemple en accord avec "Découvrez comment". 
Les liens du footer verticaux seulement s'il y a plusieurs colonnes. 
Accompagner la flèche d'un sous-titre "Voir un autre exemple"

**Comment by ThibautGery** [comment]
J'aime bien mais c'est un peu trop gris

**Comment by LeoColomb** [comment]
Question surement naïve, mais il n’existe pas de framework "officiel" servant de base à tous ces sites `*.gouv.fr` qui suivrait une charte graphique "officielle" ?

**Comment by MattiSG** [comment]
Pas encore  :wink:

**Comment by LeoColomb** [comment]
Merci pour la réponse !
Et il ne faudrait pas commencer par ça ? :innocent:

**Comment by MattiSG** [comment]
Non, pas dans une approche lean. Si on commence par faire le « meta » qui unifiera tout pour le futur, on va forcément se planter car on n'aura pas accumulé assez d'informations sur ce qui est commun.
Émergence > planification.
