### ISSUE TITLE
Utiliser le parser de Markdown de GitHub dans Jekyll

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#202]
La prévisualisation sur GitHub n'a pas le même rendu Markdown que le moteur de production de GitHub Pages, ce qui freine la contribution en ligne (exemple dans #201 _(EDIT : corrigé, était #200)_).

**Comment by Morendil** [comment]
Je ne comprends pas cette issue, et pourtant j'avais un peu regardé #200. Tu peux préciser l'exemple de différence entre les deux rendus? Dit autrement, quel test s'agit-il de faire passer?

Je ne vois pas non plus ce qu'il faudrait faire pour corriger.

**Comment by MattiSG** [comment]
Pardon, mauvaise référence ! C'était #201. Je corrige au-dessus.

Les retours à la ligne ne sont pas aussi souvent nécessaires en GitHub flavoured qu'avec Kramdown.

**Comment by Morendil** [comment]
C'est le même topo pour #247? (J'essaie de me faire une idée de l'impact du problème et de l'énergie à consacrer à le résoudre.)

**Comment by MattiSG** [comment]
Oui !

**Comment by Morendil** [comment]
Potentiellement utile: https://github.com/karlcow/markdown-testsuite

**Comment by Morendil** [comment]
Il semblerait que le moteur Markdown utilisé pour le rendu des README.md est RedCarpet: https://github.com/github/markup - on peut supposer que c'est le même qui prend en charge la fonction Preview. Je crains qu'on ne soit coincés. Je vais créer une issue sur https://github.com/github/markup à tout hasard.

**Comment by Morendil** [comment]
Cf: https://github.com/github/markup/issues/900

**Comment by MattiSG** [comment]
On est coincés ici. Voir github/markup#900 pour les avancées sur ce sujet.

**Comment by MattiSG** [comment]
Il faudrait faire une PR dans https://github.com/gettalong/kramdown/issues/359.

**Comment by Morendil** [comment]
Un fix est inclus dans la prochaine version de kramdown: https://github.com/gettalong/kramdown/pull/358

**Comment by MattiSG** [comment]
Reste donc à attendre la publication de `kramdown` et la mise à jour de `github-pages`…

**Comment by MattiSG** [comment]
On ne peut rien faire ici, je ferme l'issue. Suivre https://github.com/github/markup/issues/900 pour les mises à jour.
