### ISSUE TITLE
Ajouter lien "bonnes pratiques"

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#24]
https://github.com/sgmap/bonnes-pratiques/

**Comment by Morendil** [comment]
Apparemment @krichtof l'a découvert tout seul: peut-être que ça répond à la question... par la négative.

**Comment by MattiSG** [comment]
Pour moi il y a un enjeu de visibilité en externe de nos manières de faire plus que de découvrabilité en interne.

**Comment by Morendil** [comment]
Fixed by #245
