### ISSUE TITLE
Améliorer la description de chaque page

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#259]
Exemple :
- Les pages de fiches produit devraient contenir la mission de la startup.

**Comment by Morendil** [comment]
De mémoire l'intention était de favoriser la présentation sur les réseaux sociaux, ou autres sites qui peuvent nous envoyer du trafic, comme implémenté par #386.

Qu'est-ce qu'il faudrait encore faire pour avoir un résultat satisfaisant ? Ou est-ce qu'il y a une autre intention ?

**Comment by Morendil** [comment]
Je ferme en l'absence de tâches précises mais n'hésite pas à rouvrir avec une todo list si besoin.
