### ISSUE TITLE
Proposer une version anglaise du site

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/beta.gouv.fr#260]
Suite au lancement d'api.gouv.fr, j'ai remarqué qu'il y avait eu presque 3000 visites (sur 13000) qui ont été faite depuis l'étranger. D'un point de vue communication, on peut cibler un peu plus les pays anglophones

**Comment by fpagnoux** [comment]
Oui, depuis qu'on communique de manière plus large, ça devient un vrai besoin.

**Comment by MattiSG** [comment]
Demande d’évaluation des possibilités de mobilisation de traducteurs professionnels envoyée à la com.

> Il n’y a pas beaucoup de contenu, et il sera amené à changer régulièrement. On peut certainement assurer les modifications en allant, et on devra dans tous les cas tout relire car il y a plusieurs termes métier, mais une première passe par des professionnels serait certainement appréciée.

**Comment by odtvince** [comment]
Avons-nous eu un retour ? 
Sinon je peux m'y coller et proposer un premier jet à votre relecture.

**Comment by MattiSG** [comment]
La com utilise https://webgate.ec.europa.eu/mtatec/. J'ai un compte.

**Comment by MattiSG** [comment]
@odtvince préfères-tu que le premier jet soit fait par une machine sur lequel on discute, ou préfères-tu faire le premier jet toi-même ?

**Comment by Morendil** [comment]
La proposition de @ThibautGery est une bonne occasion de relancer cette discussion!

Concrètement ça ressemblerait à quoi "une version en anglais", c'est un site à part (genre en.beta.gouv.fr), un site 100% multilingue avec des petits drapeaux pour switcher fr/en, juste des versions fr et en de certains de nos contenus?

Pour le dire autrement, que peut-on identifier comme "baby step" qui nous mette sur une trajectoire au bout de laquelle nous aurons le rayonnement international que nous méritons? ;)

**Comment by MattiSG** [comment]
Traduire la landing page et ajouter la gestion multilingue dans un CMS qui n'est pas fait pour ça.

**Comment by ThibautGery** [comment]
Pour info j'ai rejoué la prez qu'on avait faite  pour Octo Australie, si vous faite un site en anglais, je traduit ca et je vais la jouer au meetup lean Startup de Sydney.
