### ISSUE TITLE
Lister les alumni

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#285]
La page équipe liste tous les membres de l'incubateur. Les ancien·ne·s sont absents, et certains ont quitté la structure mais sont encore listés.

(Opportunité : demande de la Cour des Comptes la liste des membres en 2016)

**Comment by odtvince** [comment]
> certains ont quitté la structure mais sont encore listés.

Is it a bug or a feature?

Plus sérieusement, couper la page en deux sections successives - équipe / alumni - devrait faire l'affaire.

**Comment by MattiSG** [comment]
> couper la page en deux sections successives - équipe / alumni - devrait faire l'affaire.

Le détail de l'issue présente le « bug ». Le titre de l'issue, le job-to-be-done, est bien *Lister les alumni*.
