### ISSUE TITLE
Afficher l'historique des membres de l'incubateur

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#286]
Représenter les entrées / sorties.

(Opportunité : demande de la Cour des Comptes d'avoir cet historique)

**Comment by odtvince** [comment]
Je ne pense pas que rendre l'appartenance à l'incubateur binaire (chacun devant être strictement dedans ou dehors) soit une bonne chose. Il y a un continuum des amis et sympathisants aux contractuels rattachés à la mission. Que la CdC veuille du noir et blanc est normal (c'est son boulot). Nous pouvons néanmoins conserver la richesse de nos niveaux de gris dans notre communication publique.

**Comment by MattiSG** [comment]
1. Courant / Alumni ≠ Dedans / Dehors. Les « dehors » ne sont simplement pas visibles.
2. Il y a quand même une réalité objective au niveau de disponibilité, d'engagement et de responsabilité des personnes selon qu'elles sont engagées dans une relation contractuelle avec la structure ou non.
3. Toutes les autres structures de type startups, incubateurs, groupe d'action… ont un écosystème de « fans », voire de contributeurs, mais ne les placent pas au même niveau que l'équipe « noyau ».

Au-delà de ces arguments, j'avoue simplement ne pas comprendre en quoi cette issue pose plus de problèmes que #285. Il s'agit simplement de transformer l'appartenance, depuis le booléen actuel, en une date. J'ai au contraire l'impression que ça représentera plus nos « niveaux de gris » que l'existant, surtout que l'influence me semble se baser dans les faits en premier lieu sur les accomplissements, et en second lieu sur l'ancienneté.

**Comment by odtvince** [comment]
Je ne nie pas la réalité objective, j'interroge notre intérêt à la mettre en exergue dans notre communication publique. J'aurais effectivement tout aussi bien pu le faire sur la #285 voire même sur la #114

**Comment by MattiSG** [comment]
Intérêt à montrer 1. la croissance et 2. qu'il est possible de travailler avec nous. Je ne vois pas en quoi des stats agrégées comme dans #286 ou #287 nous rapproche d'un organigramme.

Et, d'ailleurs, si on avait un organigramme, je serais pour le rendre lisible de l'extérieur. Si on ne veut pas représenter la réalité parce qu'elle dérange, c'est peut-être la réalité qui dérange plutôt que son modèle qu'il faut questionner… ?
