### ISSUE TITLE
Indiquer la répartition des rattachements administratifs

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#287]
Décomposer DINSIC / partenaires / indépendants / prestataires.

Demande récurrente lors de la présentation de l'Incubateur.

(Opportunité : demande de la Cour des Comptes d'avoir cette répartition)

**Comment by HelaG** [comment]
Quelle est la valeur pour nous de rendre public une notion de rattachement contractuel ( indépendants / prestataires ) à laquelle on accorde peu d'importance en interne ?

**Comment by Morendil** [comment]
"It's not a bug, it's a feature."

**Comment by MattiSG** [comment]
- On est de toute façon obligés d'avoir ce suivi quelque part, pour minimiser le fractionnement des outils autant consolider dans un seul espace.
- Transparence (demande récurrente à chaque présentation de l'incubateur, à laquelle on accepte de répondre, et on a de toute façon la donnée, autant l'éditorialiser).

En termes de représentation, et pour minimiser les risques de mauvaise interprétation, je ne vois pas cette information comme attachée à chaque membre, mais uniquement comme un graphe de suivi de la répartition globale.

Je défends l'idée pour faire débat, mais continuons la discussion.

**Comment by HelaG** [comment]
_(demande récurrente à chaque présentation de l'incubateur, à laquelle on accepte de répondre, et on a de toute façon la donnée, autant l'éditorialiser)._
Pourquoi on nous pose régulièrement la question ? 

D'après mon expérience, cette question m'a été posée : 
- pour comprendre les conditions d'engagement qui sont "explicitées" sur [Contact](https://beta.gouv.fr/contact);
- dans une posture réactionnaire de type curiosité/défiance.

**Comment by Morendil** [comment]
On pourrait imaginer une page "l'incubateur en chiffres" - avec des données agrégées, non nominatives -  qui créerait de la transparence sans mettre en avant des différences de statut. (Et ça serait assez "cour des comptes" dans l'esprit: combien on est dans chaque catégorie, mais aussi combien ça a coûté etc.)

**Comment by MattiSG** [comment]
Je pense à un truc comme ça, _en plus_ de l'existant, sans jamais afficher le rattachement sur les fiches individuelles :
![capture d ecran 2016-07-27 a 18 58 17](https://cloud.githubusercontent.com/assets/222463/17184397/25835972-542c-11e6-91d9-d91f8e9bfc94.png)

**Comment by MattiSG** [comment]
A priori les :+1: sur mon message ci-dessus montrent un accord sur le rendu.

Pour l'implémentation, le plus simple serait de lister le rattachement dans les fiches individuelles des membres (ajouter une propriété `contract` dans le YAML front-matter des fiches `_author`). Cela signifierait donc que cette information serait visible dans GitHub (mais jamais mise en avant dans le site).

Je suis personnellement ok avec ça, car :
- Cette information n'est pas secrète et une question directe obtient une réponse.
- Cette information peut être facilement trouvée par d'autres moyens (LinkedIn).
- Je ne vois pas comment l'anonymiser correctement au vu des faibles volumes (tiens, une nouvelle personne dans l'incubateur, le même mois telle catégorie fait +1).

Est-ce que cette implémentation vous gêne ?

**Comment by Morendil** [comment]
Non ça se tient. Comment comptes-tu obtenir la profondeur historique a partir de la donnée a l'instant t? (Je vois assez bien comment on pourrait dessiner un histogramme a l'instant t mais pas comment on reconstitue l'évolution sur 2014-2016 et comment on pourrait ensuite l'actualiser.)

**Comment by MattiSG** [comment]
Via #285 puis #286.

**Comment by odtvince** [comment]
Comment (pourquoi ?) différencier indépendants refacturés par une SSII ou employés de cette SSII ? Contractuellement vu du SGMAP, il n'y a pas de différence me semble-t-il.

**Comment by MattiSG** [comment]
Parce qu'on dit souvent qu'on travaille avec des indépendants, que c'est une réalité, que le comportement et le sentiment d'appartenance des personnes est souvent influencé par ce statut, et que représenter ces « niveaux de gris » reflète plus notre réalité que ne représenter qu'une appartenance administrative ?

**Comment by jdesboeufs** [comment]
Et ceux qui ont changé 3x de statut en 2 ans ?
À titre personnel je ne vois pas ce que ce genre d'information apporte à notre public, à part du bruit pour les sangs-impurs.

**Comment by ppezziardi** [comment]
lol, on prendra le dernier statut ;)

même si cela m'a gonflé au début, je soutiens l'entreprise de gestion à un seul endroit des données que nous gérions dans https://docs.google.com/spreadsheets/d/1pZYJvjUeMPF2oWzDOp6SC-CECcb3zmt5xq-udeEcELg/edit#gid=1009001020

cette catégorie était déjà gérée, car effectivement il y a du public pour, et c'est notre storytelling "ce n'est pas une révolution plaquée de l'extérieur, mais une alliance nouvelle entre agents publics, indépendants et SSII décidés à travailler en direct avec l'usager" qui amène les curieux.

Ma crainte : une fois dans le www, comment peut-on faire des traitements Excel sur la donnée ?

**Comment by MattiSG** [comment]
> comment peut-on faire des traitements Excel sur la donnée ?

Tout est en YAML, donc structuré. Dès qu'on aura des cas d'usage, on pourra écrire un petit extracteur qui consolide la donnée.

**Comment by ppezziardi** [comment]
Pour que j'abandonne la feuille RH : saisie des dates de fin de contrat pour avoir le tableau "nombre de jours avant pb" de chaque membre actif.

**Comment by jdesboeufs** [comment]
Bon alors après avoir mieux étudié le sujet :

Ma crainte était qu'on associe nominativement les membres de l'incubateur et leur statut.
Étant prestataire freelance et impliqué dans plusieurs _instances consultatives_ au nom d'Etalab ou de la DINSIC j'ai en effet un peu peur que mes positions soient affaiblies.

Que le détail soit dans des fichiers YAML, et qu'on affiche une répartition me va tout à fait.
