### ISSUE TITLE
Déployer les pull requests sur un serveur temporaire

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#291]
En tant que contributeur,
Je peux tester mes modifications dans un serveur équivalent au serveur de production,
Pour déterminer si d'autres ajustements sont nécessaires

- - - - - -

Dupliquer ce qu'a fait @ThibautGery dans sgmap/api.gouv.fr#157 :+1:

**Comment by Morendil** [comment]
- [ ] Créer un compte Heroku pour l'Incubateur
- [ ] Ajouter les fichiers manquants: Procfile, Gemfile.lock...
- [ ] Ajuster la configuration

**Comment by Morendil** [comment]
Fixed by #301

**Comment by Morendil** [comment]
Manque:
- [ ] Mettre à jour la doc (cf api.gouv.fr)

**Comment by Morendil** [comment]
Un grand merci à @ThibautGery qui sait partir en beauté :)

**Comment by MattiSG** [comment]
💃 Top !!

**Comment by MattiSG** [comment]
Ça marche moyen  ;)

![capture d ecran 2016-09-06 a 16 27 12](https://cloud.githubusercontent.com/assets/222463/18277452/d8a01bca-744e-11e6-86df-681660f4f603.png)

**Comment by Morendil** [comment]
Hmm, je n'ai pas ce souci sur #305 - c'était quoi #303? Elle n'existe plus...

**Comment by MattiSG** [comment]
Ok, je ne reproduis pas non plus sur #306. Supposons qu'il y a eu un cas particulier…

**Comment by MattiSG** [comment]
Ça ne fonctionne pas sur #309…
https://betagouv-pr-309.herokuapp.com
![capture d ecran 2016-09-09 a 14 54 29](https://cloud.githubusercontent.com/assets/222463/18387513/5543fb06-769d-11e6-8709-3d54bcb1bb0c.png)

**Comment by MattiSG** [comment]
Apparemment lié à https://status.heroku.com/incidents/941.
