### ISSUE TITLE
Abonner les partants à la ML alumni@ et les désabonner de incubateur@

### ISSUE THREAD

**Issue by Morendil** [sgmap/beta.gouv.fr#299]

**Comment by Morendil** [comment]
...sauf que je n'ai pas trop d'idée de la façon dont on peut matcher les adresses mail des gens, à moins de les préciser dans le .md

**Comment by MattiSG** [comment]
Ah mince, dans l’API OVH on n’a que les mails, pas de nom / prénom ?
Sinon, vu qu’on a déjà formalisé ça, on peut dire que l’adresse est `downcase(accent_fold($nom.$prenom))@beta.gouv.fr`, non ? À cause de l’accent folding, c’est une injection, mais c’est peut-être suffisant… ?

**Comment by Morendil** [comment]
...pour les membres, oui. Pour les anciens ça va être plus dur.

**Comment by Morendil** [comment]
...en fait non, pour les membres non plus: peu utilisent leur adresse @beta.gouv.fr.

**Comment by MattiSG** [comment]
La doc sur le wiki a bien fonctionné pour @glazzara :wink:

**Comment by Morendil** [comment]
Le code qui prend en charge cette fonctionnalité est poussé sur https://github.com/sgmap/betaGouvBot et prêt à partir en prod, l'appli Heroku est déjà équipée des clés d'API d'OVH.

J'ai créé des redirections supplémentaires dans OVH de façon à ce que les mailing listes "incubateur" et "alumni" puissent être constituées exclusivement d'adresses en @beta.gouv.fr; par contre il y a quelques "trous dans la raquette":

- je n'ai pas d'adresse mail pour Arnaud Kleinpeter
- quelques personnes sont inscrites sur alumni@beta.gouv.fr qui n'apparaissent pas sur la page "communauté" (5 personnes au total), or la fonctionnalité décrite ci-dessus implique qu'ils seront supprimés de la ML alumni; on peut les garder dans la boucle en les inscrivant à une autre ML (friends@beta.gouv.fr?) voire à notre liste Mailjet (?)

J'ai conservé une copie des 2 ML par sécurité. Sous réserve d'un avis favorable c'est prêt pour la prod.

**Comment by MattiSG** [comment]
Je pense qu'on demande aux 5 personnes s'ils souhaitent apparaître sur le site et donc être inscrits à la ML ou non, ainsi qu'à @nanocom.

**Comment by nanocom** [comment]
mon mail perso : arnaud.kleinpeter@gmail.com
merci !

**Comment by Morendil** [comment]
Finalement suite à consultation sur Slack l'option retenue est de ne pas toucher aux emails qui ne correspondent pas à une fiche sur beta.gouv.fr.

Implémenté dans betaGouvBot.
