### ISSUE TITLE
Mettre en valeur nos produits qui ne sont pas des startup d'Etat

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/beta.gouv.fr#300]
L'idée est de référencer les produits issus de l'incubateur mais qui ne suivent pas la méthodologie startup d'Etat. Je pense tout particulièrement à :
 * [verif.site](https://verif.site/)
 * [urbaclick](http://www.opendatalab.fr/urbaclic)

**Comment by jdesboeufs** [comment]
Urbaclic est désormais une startup d'État.
Je propose que l'on ferme ce ticket, en sachant très bien que le sujet pourra revenir sur la table.

**Comment by MattiSG** [comment]
> référencer les produits issus de l'incubateur mais qui ne suivent pas la méthodologie startup d'Etat

Pour moi c'est un contresens sur `beta.gouv.fr`…
