### ISSUE TITLE
Uniformiser la capitalisation des titres

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#31]
La Bonne Boîte ou Fiches de banc ?

**Comment by odtvince** [comment]
La Bonne Boîte ou Fiches de banc ?
Les deux mon capitaine.
Mais surtout pas La bonne Boite ou Fiches de Banc.

**Comment by MattiSG** [comment]
J'ai du mal à voir la règle à appliquer, du coup  :confused: 
À la lecture, c'est quand même un peu étrange :

> Prélèvement à la Source pour les Indépendants
> Marchés Publics Simplifiés
> Retraite simplifiée
> Signaux Faibles
> Data.gouv.fr
> api.gouv.fr

Actuellement, le plus grand déterminisme semble être l'auteur originel du nom de la startup…  :wink:

**Comment by odtvince** [comment]
https://fr.wikipedia.org/wiki/Usage_des_majuscules_en_fran%C3%A7ais#R.C3.A8gles_traditionnelles

**Comment by jdesboeufs** [comment]
Faisons comme La Poste, on met tout en majuscules !

**Comment by odtvince** [comment]
La Poste met tout en capitales, pas en majuscules ;-)

**Comment by MattiSG** [comment]
:+1: pour appliquer les règles habituelles référencées par @odtvince.
