### ISSUE TITLE
Uniformiser le sujet des mission statements

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#32]
> Augmenter la productivité du traitement des amendements des cabinets ministériels.

ou

> Trouvez les entreprises qui vont recruter près de chez vous.

ou

> Des outils et des méthodes au service de la modernisation de l’action publique dans l’Éducation nationale.

?

**Comment by Morendil** [comment]
> C’est un grand agrément que la diversité. Nous sommes bien comme nous sommes. Donnez le même esprit aux hommes; vous ôtez tout le sel de la société. L’ennui naquit un jour de l’uniformité.

Sur https://beta.gouv.fr/startups je suis pour l'instant plus gêné par les alignements aléatoires, liés aux tailles d'images diverses des screenshots, que je ne le suis par la diversité des formules. (Un quick win consisterait à mettre la description en haut et le screenshot optionnel en bas, après les éléments obligatoires.)

Certains cas risquent d'être douloureux à traiter, par exemple "Un clic, un taxi."

**Comment by MattiSG** [comment]
> Un clic, un taxi.

Peut-être est-ce un _slogan commercial_ plus qu'un _énoncé de mission_, ce dernier étant plus attendu sur beta.gouv.fr… ?

**Comment by Morendil** [comment]
Je comprends l'objection, mais d'un autre côté beta.gouv.fr est aussi une vitrine pour les porteurs de ces produits; ça peut être une raison d'insister pour afficher leur _slogan commercial_ dans la vitrine.

Nous avons maintenant 6 mois de recul supplémentaires. Quelques stats:
- énoncés à l'infinitif ("simplifier") : 11
- énoncés à l'impératif ("suivez") : 12
- autres : 4

Sur un plan strictement grammatical il me semble plus facile de s'aligner sur l'infinitif : changer "suivez" en "suivre" ne modifie pas le sens, changer "simplifier" en "simplifiez" est plus problématique (on rend le lecteur, qui est dans la plupart des cas un usager cible, responsable de buts qu'il ne peut pas atteindre).

C'est plus délicat si on cherche à harmoniser la nature de l'énoncé. On pourrait considérer que chaque énoncé de mission est à lire un peu comme un message de commit: on le lit précédé de "**En investissant dans ce produit l'Etat cherche à...**". Appliquer ce modèle entraînerait plus de changements (par exemple les énoncés pour Chouette, Boomerang...)

Voici une proposition à "baffer" :
- [ ] s'assurer que tous les énoncés de mission décrivent le bénéfice attendu
- [ ] formuler tous les énoncés à l'infinitif
- [ ] documenter ces règles dans CONTRIBUTING

Qu'en penses-tu? Qui d'autre faudrait-il associer à cette discussion?

**Comment by MattiSG** [comment]
J'en pense qu'il faut parler de « recommandation » plus que de « règle ». L'objectif est de faciliter la lecture et la découverte dans la vue « portefeuille », il ne faut pas que les startups le vivent individuellement comme une contrainte insurmontable.

> Qui d'autre faudrait-il associer à cette discussion ?

Toutes les personnes qui ont rédigé leur mission statement actuel  :wink:

**Comment by MattiSG** [comment]
Mais oui, commençons par faire une branche de proposition où tout est à l'infinitif, et discutons sur cette base-là plutôt que sur l'idée du changement, qui va faire râler, ou sur des règles théoriques, qui vont agacer.

**Comment by Morendil** [comment]
Fixed by #403
