### ISSUE TITLE
Tester automatiquement l'ajout des données employeur

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#327]
Évite des ajouts tardifs comme #326.

Alternative : augmenter la résilience de l'algorithme de présentation, car l'absence d'une donnée empêche le graphe d'être rendu correctement.

**Comment by Morendil** [comment]
Une piste: http://www.kuwata-lab.com/kwalify/

**Comment by MattiSG** [comment]
Sinon https://github.com/sgmap/beta.gouv.fr/blob/845d483649801eb48d6f70554b53ba50dd690334/_includes/owner.html ;)

**Comment by Morendil** [comment]
Nice. A mon avis c'est jouable jusqu'au 3è champ à valider comme ça... "three strikes and you refactor"

**Comment by MattiSG** [comment]
Ce sera le troisième  ;-P
