### ISSUE TITLE
associer à chaque startup une photo

### ISSUE THREAD

**Issue by ppezziardi** [sgmap/beta.gouv.fr#33]
que l'on utilisera en vignette dans la liste, et en 400*400 environ dans la fiche produit

**Comment by MattiSG** [comment]
Ouais ! Dès qu'on aura un·e graphiste pour en trouver des belles ET liées au sujet ? :wink:

**Comment by ppezziardi** [comment]
ben non, on n'a pas le choix que d'assumer nos home pages ;)

**Comment by laem** [comment]
Je propose des illustrations comme [celle-là](https://atom.io/) pour chaque startup
