### ISSUE TITLE
Rendre les identifiants de phase insensibles à la casse

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#335]
Faciliter la contribution en évitant des erreurs comme dans #334.

**Comment by Morendil** [comment]
J'ai jeté un oeil et je pense que ça exigerait beaucoup de boulot pour peu de bénéfice... On ne peut pas utiliser un filtre downcase dans une expression where, je ne vois pas de piste d'implémentation simple.

**Comment by MattiSG** [comment]
@Morendil pas de souci pour nettoyer régulièrement les vieilles issues, mais merci de laisser un mot (même court) pour expliquer le pourquoi de la fermeture. C'est compliqué à tracer, sinon :wink:

**Comment by Morendil** [comment]
Pas de proposition depuis 1 mois et valeur perçue faible par rapport à l'effort estimé.
