### ISSUE TITLE
Permettre le choix du suivi de navigation

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#342]
Le cookie Piwik est systématiquement déposé.

Il faudrait ne pas traquer sans recueil du consentement.
Malheureusement, cela revient à perdre la capacité à suivre le taux de rebond et les backlinks vers des pages spécifiques.

Deux options me semblent possibles :

1. Charger dynamiquement Piwik si le [DNT](https://fr.wikipedia.org/wiki/Do_Not_Track) est activé.
2. Faire du suivi côté serveur, ce qui accélèrera également le chargement, mais qui implique de sortir de l’hébergement GitHub Pages.

Todo
-----

- [x] Anonymiser l'IP.
- [x] Ne pas proroger les cookies. — #343
- [x] Permettre l'opt-out. — #343

Communication
-------

- [x] Mail du 7 octobre 2016 à 22:24.

**Comment by Morendil** [comment]
La CNIL a créé des exemptions explicites à l'obligation d'afficher la bannière de consentement au cookies préalablement au dépôt d'un cookie, et l'outil Piwik que nous utilisons est justement visé par une telle exemption...

https://www.cnil.fr/fr/solutions-pour-la-mesure-daudience

**Comment by MattiSG** [comment]
Génial, merci @Morendil !!

Pour être exempté, et sur la base du document, il faut donc : 
- [ ] Ne pas proroger les cookies.
- [ ] Anonymiser l'IP.
- [ ] Permettre l'opt-out.

**Comment by Flightan** [comment]
Pour paramétrer Piwik correctement: https://www.cnil.fr/sites/default/files/typo/document/Configuration_piwik.pdf

**Comment by Morendil** [comment]
Opt-out en cours via #343, les deux autres relèvent du paramétrage de Piwik.

**Comment by Morendil** [comment]
Corrigé par #343, @MattiSG je réponds ou tu réponds au mail à l'origine de cette issue?

**Comment by MattiSG** [comment]
@Morendil je prends.

**Comment by MattiSG** [comment]
Done.

**Comment by CookieCheck** [comment]
Bonjour,
Bonsoir à tous,
Si vous lisez bien la page de la CNIL citée par Morendil (https://www.cnil.fr/fr/solutions-pour-la-mesure-daudience) l'exemption concerne l'obtention d'un consentement exprès et non celui de ne pas afficher la bannière. Il faut alors continuer à afficher une bannière et informer précisément et clairement ce qu'est Piwik mais le consentement reste facultatif.

**Comment by Flightan** [comment]
Bonjour, je ne vois pas de mention d'une bannière, pouvez-vous pointer vers l'article à cet effet ?

**Comment by CookieCheck** [comment]
Voila le lien sur les conditions d'utilisation des cookies sans consentement  imposant une information de la part de l'éditeur https://www.cnil.fr/fr/solutions-pour-la-mesure-daudience. Dans l'article ci-après la Cnil explique en quoi consiste l'information préalable sur les cookies et distingue bien que le moyen d'informer (c'est-à-dire la bannière et la politique cookies) est une condition indépendante de celle de l'obligation d'obtenir le consentement ou pas...https://www.cnil.fr/fr/exemple-de-bandeau-cookie

**Comment by MattiSG** [comment]
Bonjour @CookieCheck,

Sur la première page que vous mentionnez, je lis bien deux solutions exclusives :

> **1. Utiliser un outil dispensé de consentement**
> 2. Recueillir le consentement de l'internaute en cas d'utilisation d'outil non conforme

Nous en sommes d'accord, nous sommes a priori dans le cas 1. Vérifions notre éligibilité en lisant le paragraphe suivant, à savoir _Conditions pour mesurer la fréquentation sans recueillir le consentement_ :

> - L'éditeur du site doit délivrer une information claire et complète.
> - Un mécanisme d’opposition doit être accessible simplement et doit pouvoir être utilisable sur tout types de terminaux (y compris les smartphones et tablettes).

Nous le faisons via la page suivi.

> - Les données collectées ne doivent donc pas être recoupées avec d’autres traitements (fichiers clients ou statistiques de fréquentation d'autres sites par exemple).
> - Le cookie déposé doit servir uniquement à la production de statistiques anonymes.
> - Le cookie ne doit pas permettre de suivre la navigation de l’internaute sur d’autres sites.

Oui (pour la dernière, ce n'est même pas possible techniquement).

> - L’adresse IP permettant de géolocaliser l’internaute ne doit pas être plus précise que l’échelle de la ville. Concrètement les deux derniers octets de l’adresse IP doivent être supprimés.

Oui, notre instance est bien configurée ainsi.

> - Les cookies permettant la traçabilité des internautes et les adresses IP ne doivent pas être conservés au-delà de 13 mois à compter de la première visite.

Oui, comme vous pouvez le voir explicitement dans #343.

### Dans la mesure où nous remplissons toutes ces conditions, nous sommes bien dispensés du recueil du consentement préalable au dépôt du cookie.

Dès lors, la seconde page que vous mentionnez, qui répond à la question « _Comment_ recueillir valablement le consentement des internautes aux cookies et traceurs de votre site ou application web ? » ne nous concerne pas, puisque nous n'avons _pas_ à recueillir ce consentement.

Merci en tous cas de vous intéresser d'aussi près à ce sujet important  😃

**Comment by laem** [comment]
> le moyen d'informer (c'est-à-dire la bannière et la politique cookies) est une condition indépendante de celle de l'obligation d'obtenir le consentement ou pas

C'est globalement comme ça que je comprend les textes (le deuxième article CNIL est donc mal titré) mais pour moi la question (qui tranche ce débat) est : *est-ce que mettre un lien " Suivi d’audience et vie privée" dans le footer c'est "informer les internautes de la finalité des cookies" ?*. J'ai bien peur que ce soit trop discret et surtout invisible car en dehors de la fenêtre initiale.

**Comment by MattiSG** [comment]
> les textes (le deuxième article CNIL est donc mal titré) 

Lesquels ? La CNIL me semblait une assez bonne source sur ce sujet  :wink:

> est-ce que mettre un lien " Suivi d’audience et vie privée" dans le footer c'est "informer les internautes de la finalité des cookies" ?

D'après https://www.cnil.fr/fr/solutions-pour-la-mesure-daudience, la question me semble plutôt être « la page Suivi d’audience et vie privée délivre-t-elle une information claire et complète ? ».

**Comment by Morendil** [comment]
D'autres pages du site de la CNIL sont encore plus explicites sur leur traitement "à deux vitesses", par exemple celle-ci: https://www.cnil.fr/fr/cookies-comment-mettre-mon-site-web-en-conformite qui fait clairement la distinction entre le cas où l'on utilise un outil exempté de consentement et le cas où l'affichage d'un bandeau est recommandé.

Plus largement, mon raisonnement (qui n'est pas celui d'un juriste) consiste à observer que pour la loi "informatique et libertés", plus précisément son [article 32](https://www.cnil.fr/fr/loi-78-17-du-6-janvier-1978-modifiee#Article32), utiliser Piwik (ou plus formellement faire usage "à bref délai d'un procédé d'anonymisation préalablement reconnu conforme aux dispositions de la présente loi par la Commission nationale de l'informatique et des libertés”) **dispense de quelque chose de substantiel**.

Je ne peux donc pas adhérer à la conclusion que les sites qui utilisent Piwik pour collecter des données anonymes et utiles seulement à la mesure d'audience sont astreints exactement à la même chose que ceux qui déposent des cookies pour pister l'usager d'un site marchand à un autre et lui proposer des publicités ciblées en fonction de son comportement. En particulier, je ne crois pas à la notion d'une **obligation légale à l'auto-défiguration**, et j'observe que si le site de la CNIL parle souvent d'un "bandeau" ce terme n'apparaît nulle part dans la loi, et ne constitue à mon sens (mais je rappelle que je ne suis pas juriste) qu'une recommandation sans valeur légale.

La loi précise par ailleurs que les dépôts de cookie "ne peuvent avoir lieu qu'à condition que l'abonné ou la personne utilisatrice ait exprimé, après avoir reçu cette information, son accord *qui peut résulter de paramètres appropriés de son dispositif de connexion ou de tout autre dispositif placé sous son contrôle*.” (C'est moi qui ajoute du gras.) Il se trouve que les navigateurs proposent généralement un paramétrage pour accepter ou non les cookies déposés par les sites, et que dès lors les sites qui utilisent des cookies "normaux" pour tracer l'utilisateur (par opposition à un pixel traceur ou cookie flash) sont automatiquement conformes à la loi. Nous respectons quand même certaines recommandations de la CNIL telles qu'informer le visiteur de notre identité, de la finalité de nos cookies, de la possibilité de se soustraire au tracking.

Bref, il me semble que faisons largement plus que le nécessaire pour nous mettre en conformité avec l'esprit et la lettre de la "loi cookie", et que l'énergie des différents intervenants serait plus efficacement dirigée vers d'autres nobles causes. :)

**Comment by MattiSG** [comment]
@ThomasMenant Un avis ?

**Comment by ThomasMenant** [comment]
ça me demande un peu d'instruction, j'essaie de vous faire ça asap

**Comment by laem** [comment]
> Je ne peux donc pas adhérer à la conclusion que les sites qui utilisent Piwik pour collecter des données anonymes et utiles seulement à la mesure d'audience sont astreints exactement à la même chose que ceux qui déposent des cookies pour pister l'usager d'un site marchand à un autre et lui proposer des publicités ciblées en fonction de son comportement.

Dans le premier cas, information _et_ pose du cookie de toute façon. 
Dans le second cas : information _puis_ pose du cookie suite à une action de l'utilisateur (la poursuite de la navigation est une de ces actions). Je ne sais pas si c'est substentiel mais le second est plus contraignant.

> j'observe que si le site de la CNIL parle souvent d'un "bandeau" ce terme n'apparaît nulle part dans la loi, et ne constitue à mon sens (mais je rappelle que je ne suis pas juriste) qu'une recommandation sans valeur légale.

Si la notion "information de l'utilisateur" implique la présence du texte dans la zone visible par défaut à l'ouverture du site dans le navigateur, alors le bandeau est la meilleure solution pour s'y conformer tout en reléguant cette information, secondaire par rapport au contenu du site, en bas de l'écran.

**Comment by MattiSG** [comment]
> Si la notion "information de l'utilisateur" implique la présence du texte dans la zone visible par défaut à l'ouverture du site dans le navigateur

Il me semble justement que @Morendil a expliqué en longueur plus haut que ce n'est pas le cas…

**Comment by MattiSG** [comment]
Ce que j'ai l'impression que ce que nous cherchions à démontrer, c'est qu'il est possible de remplir les conditions exigées par la CNIL et par le respect de la vie privée des visiteurs en configurant correctement l'outil de suivi, en permettant l'opt-out, et sans afficher de bandeau  😄

@laem Que cherches-tu à démontrer exactement ? Si tu penses que notre interprétation est erronée et qu'il faut impérativement présenter un bandeau à l'utilisateur, peux-tu citer les textes autres que la recommandation Cookies qui te font penser cela ?

Car jusqu'ici, il y avait [consensus](https://github.com/sgmap/beta.gouv.fr/issues/342#issuecomment-257839963), j'ai [détaillé](https://github.com/sgmap/beta.gouv.fr/issues/342#issuecomment-256594238) notre lecture de la recommandation Cookies et @Morendil a [souligné](https://github.com/sgmap/beta.gouv.fr/issues/342#issuecomment-257839963) que la loi n'impose pas de dispositif de manière plus précise. Le fait d'avoir « peur que ce soit trop discret » est un point honorable, et rien n'empêche de mettre un bandeau (ou un `<marquee>` !) sur d'autres applications 😃

Mais, en l'occurrence, les contributeurs de beta.gouv.fr ont considéré qu'il était pertinent d'éviter aux visiteurs d'avoir à cliquer sur un bandeau. Peut-on essayer de conserver cette conversation centrée sur démontrer que cette interprétation est _possible ou non_ plutôt que sur si elle est _souhaitable_ ? Ça peut être un point intéressant, mais on ne s'en sortira pas si on mélange les deux  :wink:

**Comment by laem** [comment]
> @laem Que cherches-tu à démontrer exactement ?

J'ai expliqué mes doutes sur l'interpretation qui vous conduit à penser qu'il est possible d'informer l'utilisateur sur une page secondaire (en d'autres termes, lui permettre de s'informer plutôt que de l'informer). Le fait que ce soit souhaitable ou non est évidemment un autre débat. 

Ce n'est que mon avis, et comme le dit @Morendil, je ne suis pas juriste !

**Comment by MattiSG** [comment]
Ok, merci d'avoir partagé ton avis.

**Comment by MattiSG** [comment]
On attend donc l'éclairage de @ThomasMenant.

**Comment by ThomasMenant** [comment]
Salut à tous,

Vous voyez comme le droit, c'est cool ! :dancing_men: 
A vrai dire, vous vous posez une question qui est toujours ouverte, donc je vais ramer. 

En guise d'introduction, sachez que la politique autour des cookies vient de l'Union européenne suite à la modification de la directive de 2002 par une nouvelle [directive en 2009](http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2009:337:0011:0036:fr:PDF). A noter que le récent règlement européen, lui ne s'entend pas sur la question. Donc tous nos amis européens sont comme nous !

Pour gérer "l'implémentation" de cette modification dans le droit français, la CNIL a proposé une [délibération](https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000028380230). C'est la version non vulgarisée des différents éléments du site de la CNIL que vous avez cités. Comme le texte de la directive, elle n'est pas réellement limpide.

Pour en revenir à votre discussion, elle connait divers développements, je vous en propose quelqu’un (vous aimez les sources) : 
- Janvier 2013 : http://www.village-justice.com/articles/Cookies-mesure-audience-recueillir,13712.html
- Avril 2014 : http://www.village-justice.com/articles/Comment-conformer-usage-des,16737.html
- Mars 2016 : http://www.village-justice.com/articles/Peut-concilier-protection-vie,21746.html

Ce qu'on peut retenir, c'est qu'il y a deux questions différentes : 
1. L'obligation d'information de l'usager 
2. Le recueil de consentement de l'usager

Le point 2. est assez bien documenté : la CNIL et ses homologues européens ont pris une position commune qui consiste à dire que certains outils peuvent être utilisés sans recueil du consentement. C'est le cas de Piwik, à condition qu'il soit configuré [conformément aux recommandations de la CNIL](https://www.cnil.fr/sites/default/files/typo/document/Configuration_piwik.pdf).

Le point 1. est plus obscur _a priori_. 
Contrairement à ce que j'ai pu lire dans le thread, la loi est claire sur ce point : il faut informer l'usager. La question qui se pose est de savoir comment on informe cet usager, c'est à dire à quel moment la "non-défiguration du site" ne nuit plus à la "bonne information de l'usager". C'est pour cela que vous avez un débat mouvementé, parce que c'est très subjectif... et seul le juge peut le trancher.

Il faut tout de même savoir que ces histoires de "bandeaux" ont déjà donné lieu à des sanctions (certes pas en France et certes pas non plus sur le sujet précis qui nous intéresse). Néanmoins, ça nous permet d'avoir quelques informations complémentaires et [troll:mode "on"] les deux articles peuvent être lus comme se contredisant sur notre sujet de discussion, [la sanction en Espagne](http://www.village-justice.com/articles/Les-sanctions-Espagne-cas-non,21241.html) /  [c'est plus clair ? bah non](http://www.village-justice.com/articles/consentement-pour-usage-cookies,19486.html)

Tout ça à cause d'une petite phrase : 
"> Ces dispositions ne sont pas applicables si l'accès aux informations stockées dans l'équipement terminal de l'utilisateur ou l'inscription d'informations dans l'équipement terminal de l'utilisateur :
A - soit a pour finalité exclusive de permettre ou faciliter **la communication par voie électronique** ;
B - soit est strictement nécessaire à la fourniture d'un service de communication en ligne à la demande expresse de l'utilisateur. >" 

Bon le A est tellement vague que je n'ose pas imaginer ce qu'il y a derrière.
Pour le B, la logique sous-tendue est de dire : j'utilise Piwik -> Il est bien configuré -> Je n'informe pas l'usager parce qu'il souhaite utiliser mon service puisqu'il est toujours sur mon site et qu'il n'est pas parti.
C'est un raisonnement qu'on peut retrouver chez certains acteurs du e-commerce ou chez certains "anciens".

Juridiquement ça peut se défendre.

Après, comme tout cela est subjectif, je vous livre mon sentiment en m'adossant sur ce que propose la CNIL, j'aurai tendance à considérer que des deux étapes "du bandeau" présentée [ici ](https://www.cnil.fr/fr/exemple-de-bandeau-cookie) l'étape 1 "informer sur les cookies utilisés et leur finalités" s'applique pour nous. Ce lien peut renvoyer vers une page permettant l'opposition au traçage ou présentant des outils d'opposition (là aussi [solution ](https://www.cnil.fr/fr/cookies-comment-mettre-mon-site-web-en-conformite)évoquée par la CNIL).

Vous devez donc correctement informer l'usager. Là vous me dites "oui ok mais comment ?" et c'est là qu'on retombe dans le subjectif (ce qui donne des bandeaux très différents : cf le [petit](http://eur-lex.europa.eu/homepage.html?locale=fr) vs [le gros](http://www.consilium.europa.eu/fr/policies/data-protection-reform/data-protection-regulation/).

Vous prendrez donc une décision que je pourrai défendre "juridiquement parlant" que vous mettiez un bandeau (large ou fin), un élément textuel ailleurs sur la page ou un lien en footer (bien qu'honnêtement c'est pas ce qui me semble le plus correct).

Je vous ai donc fait une superbe réponse de juriste. ^^

En creux, la question que cela pose - et celle-là, elle est uniquement pour vous - c'est votre approche du sujet, et notamment le niveau de transparence que vous souhaitez afficher à l'usager et le caractère d'exemple (ou non) que vous souhaitez incarner.

**Comment by MattiSG** [comment]
Ok, on a donc une réponse définitive sur si l'implémentation actuelle est _possible_ juridiquement.

Je pense que cette conversation est close, et qu'on peut si on le souhaite ouvrir un débat indépendant sur si et comment on souhaite améliorer le niveau d'information actuel. Ce débat peut se faire soit dans une autre issue, soit IRL, soit sur 🔒Slack.

Merci à tous pour votre participation.
