### ISSUE TITLE
Alertes mail sur fin de période AUTHOR

### ISSUE THREAD

**Issue by ppezziardi** [sgmap/beta.gouv.fr#348]
Une eMail est envoyé à tout _author qui voit sa date de sortie passer à J-10 de today() et un autre à J-1.
Le mail inclut un lien direct pour modifier son profil (exemple : https://github.com/sgmap/beta.gouv.fr/edit/gh-pages/_author/Tommy.md )

et indique précisément les 2 clics à faire : update puis create PR.

**Comment by Morendil** [comment]
On a pas les emails dans les fiches actuellement. Pour l'instant ce que j'ai [codé](https://github.com/sgmap/betaGouvBot) va envoyer un mail à contact@beta.gouv.fr pour signaler qu'il y a des gens qui arrivent à l'échéance.

Si on inclut les emails dans les fiches ça permettrait de gérer aussi les abonnements et désabonnement des ML incubateur. Par contre ça peut poser un souci à certains sur le plan vie privée et exposition au spam.

**Comment by MattiSG** [comment]
Commençons avec contact.

On verra après si on fait des inférences. On pourrait tout à fait uniformiser les ID pour qu’elles aient le format des mails :)

**Comment by MattiSG** [comment]
@Morendil Si c'est traité dans `betaGouvBot`, peux-tu documenter le dépôt et le comportement ? :)

**Comment by Morendil** [comment]
Yep.

- [ ] documenter [ici](https://github.com/sgmap/beta.gouv.fr) le rôle de [betaGouvBot](https://github.com/sgmap/betaGouvBot)
- [ ] intégrer la PR de Mauko sur betaGouvBot
- [ ] ajouter un README à betaGouvBot

**Comment by MattiSG** [comment]
Up ? :wink:

**Comment by Morendil** [comment]
On a terminé avec Mauko, je ferme l'issue ici et j'en ouvre de nouvelles sur sgmap/betaGouvBot pour refléter la demande initiale de @ppezziardi.
