### ISSUE TITLE
Rendre visible la date de démarrage d'une start-up

### ISSUE THREAD

**Issue by HelaG** [sgmap/beta.gouv.fr#358]
Suite à l'atelier en séminaire, afficher le T0 de la phase d'investigation pour donner de la visibilité (notamment sur la promesse des 6 mois)

**Comment by Morendil** [comment]
Je propose qu'on revisite cette issue à la prochaine création d'une fiche Startup, je la laisse ouverte entre-temps.

**Comment by Morendil** [comment]
Suite à la PR pour la fiche Réserve Civique, je ferme: on utilise trop rarement le statut "investigation" pour que ça vaille la peine. On pourra rouvrir si on aborde à nouveau lors d'un atelier la question de la représentation sur le site du cycle de vie des startups.

**Comment by MattiSG** [comment]
> on utilise trop rarement le statut "investigation" pour que ça vaille la peine

Je ne comprends pas l'argument : de la même manière qu'on peut lister une Startup a posteriori du début de son investigation, on peut tout aussi bien donner sa date de début a posteriori, non ?

**Comment by Morendil** [comment]
OK, mon commentaire n'est pas forcément clair sans doute parce que ce n'est pas clair dans ma tête non plus. Je supposais implicitement qu'on affichait cette date seulement lorsque la fiche était dans le statut "investigation" seulement; en fait ça a aussi du sens en "construction".

Mais ce n'est pas la seule chose qui me gêne pour formuler une proposition d'implémentation concrète. Pour utiliser l'exemple qu'on a sous la main, à quand faudrait-il faire remonter la date de début de la phase d'investigation pour Réserve Civique ? Il me semble qu'elle remonte à plus loin que le 23/3.

A l'autre extrémité, je ne vois pas bien comment "donner de la visibilité sur la promesse des 6 mois". Par ailleurs, ça n'a plus de sens d'afficher ce délai lorsqu'on a basculé en "consolidation", mais il faudrait aussi expliciter pourquoi c'est le cas.

**Comment by MattiSG** [comment]
Si ça fait 6 mois que ça a débuté et que tu es encore en investigation il y a un souci.
