### ISSUE TITLE
Remarques sur la page d'accueil

### ISSUE THREAD

**Issue by laem** [sgmap/beta.gouv.fr#363]
Les remarques suivent ma lecture naturelle de la page

0. Je trouve vraiment sympa le nouveau design

1.  C'est assez frustrant de revenir sur le premier exemple après seulement deux clics sur `Voir d'autres exemples`. A l'inverse ce n'est pas réaliste de cliquer trop de fois sur ce bouton. 
*Pourquoi ne pas proposer d'explorer les 27 startups à l'utilisateur curieux qui a cliqué trois fois ?*

2. La frise capte l'attention, et donc il est probable que l'utilisateur qui est arrivé jusque là lise les popups INVESTIGATION, CONSTRUCTION etc. -> ce sera désagréable pour lui de lire le paragraphe suivant qui en est une copie. 
_Pourquoi ne pas fusionner les deux ?_ 
![selection_198](https://cloud.githubusercontent.com/assets/1177762/19682170/ac690f56-9aac-11e6-8982-e74b123c5df6.png)

3. La dimension "maturation du service" n'est pas évidente. _Ca pourrait être sympa comme ça :_ 
![selection_200](https://cloud.githubusercontent.com/assets/1177762/19682187/c15323de-9aac-11e6-8277-46270101f8cc.png)

4. Dans la version actuelle, j'ai vu que beta.gouv.fr créée des nouveaux services numériques, j'ai vu des exemples qui m'ont parlé, j'ai compris que le processus est bien documenté, on m'a remis une couche sur les phases d'une startup et là je n'ai qu'une chose en tete : l'idée géniale qui me hante depuis 1 an.  Comment je fais ? Je suis bloqué dans la navigation du site (le CTA "Une communauté" ne me convient pas).
Je trouverais intéressant de pouvoir enchaîner sur un bouton "Vous avez une idée ? Rédigez une fiche produit".

**Comment by MattiSG** [comment]
Merci @laem pour ces suggestions ! Tes PR sont les bienvenues  :wink:

**Comment by MattiSG** [comment]
Si tu n'as pas le temps de tout traiter, je te laisse au moins ouvrir des issues séparées pour chacun des points, afin de permettre priorisation et décision indépendantes.

**Comment by MattiSG** [comment]
Éclaté en #366 #367 #368 #369.

**Comment by laem** [comment]
Merci @Flightan je continuerai dessus.
