### ISSUE TITLE
Proposer d'explorer toutes les startups à l'utilisateur curieux qui a cliqué trois fois

### ISSUE THREAD

**Issue by Flightan** [sgmap/beta.gouv.fr#366]
C'est assez frustrant de revenir sur le premier exemple après seulement deux clics sur `Voir d'autres exemples`

**Comment by MattiSG** [comment]
Pas convaincu de l'utilité : que se passe-t-il quand l'usager découvre qu'il boucle ? Il scrolle vers le bas et voit le lien vers les autres.

**Comment by laem** [comment]
Ou alors, en arrivant sur site, il ne voit que les 3 captures d'écran donc pense qu'il n'y a que 3 services pour l'instant, quitte (l'autre CTA n'est pas à l'infinitif et peut sembler vouloir dire : "découvrez comment en regardant les 3 exemples suivants). 
Peut-être que je psychotte :laughing:... mais ça ne m'étonnerait pas.

**Comment by Morendil** [comment]
@MattiSG En l'état actuel des choses, le libellé de ce lien est un mensonge: après avoir cliqué deux fois tu ne verras plus **d'autres** exemples, tu reviendras sur l'exemple qui était affiché à l'origine. "Principle of least surprise" et tout.

See also http://shouldiuseacarousel.com/ and #405

**Comment by MattiSG** [comment]
Sinon, on peut aussi virer le carousel.

**Comment by Morendil** [comment]
Comme vu IRL, les fonctionnalités du site sont stables et la priorité va être donnée à la mise en valeur de nouveaux contenus sur nos apprentissages: on n'investira pas d'effort dans le design de la home pour l'instant, je ferme les issues sur ce thème.
