### ISSUE TITLE
Fusionner la frise et le descriptif des phases 

### ISSUE THREAD

**Issue by Flightan** [sgmap/beta.gouv.fr#367]
La frise capte l'attention, et donc il est probable que l'utilisateur qui est arrivé jusque là lise les popups INVESTIGATION, CONSTRUCTION etc. -> ce sera désagréable pour lui de lire le paragraphe suivant qui en est une copie. 
<img width="597" alt="screen shot 2016-10-25 at 14 46 00" src="https://cloud.githubusercontent.com/assets/1177762/19682170/ac690f56-9aac-11e6-8982-e74b123c5df6.png">

**Comment by MattiSG** [comment]
Attention à la lisibilité du contenu. Je crains que réunir les deux éléments ne nuise à la lisibilité du descriptif : le dashboard a pour objectif de mettre en avant la répartition, là où le descriptif des phases met en avant la méthode. Je ne pense pas qu'il soit simple de réunir les deux intentions dans un seul objet graphique.

Si cela était fait, il faudrait supprimer l'infobulle qui apparaît au survol.

**Comment by laem** [comment]
Je suis d'accord sur la lisibilité : 4 textes flottants c'est trop. Mais je pense que ce serait viable en la modifiant, pour qu'il n'y ait plus que deux blocs : la description de la phase (titre et explication) puis notre métrique, le nombre de startups.

**Comment by Morendil** [comment]
Je ferme pour les raisons évoquées sur #366.
