### ISSUE TITLE
Ajouter un CTA vers la documentation de la fiche produit sur la home

### ISSUE THREAD

**Issue by Flightan** [sgmap/beta.gouv.fr#368]
Dans la version actuelle, j'ai vu que beta.gouv.fr créée des nouveaux services numériques, j'ai vu des exemples qui m'ont parlé, j'ai compris que le processus est bien documenté, on m'a remis une couche sur les phases d'une startup et là je n'ai qu'une chose en tete : l'idée géniale qui me hante depuis 1 an. Comment je fais ? Je suis bloqué dans la navigation du site (le CTA "Une communauté" ne me convient pas).
Je trouverais intéressant de pouvoir enchaîner sur un bouton "Vous avez une idée ? Rédigez une fiche produit".

**Comment by MattiSG** [comment]
Comment traiterait-on ce flux entrant ?

**Comment by HelaG** [comment]
Au fur et à mesure beta.gouv doit devenir le canal d'entrée des nouvelles start-ups d'Etat mais si on veut déjà mettre en avant ce CTA d'abord faut qu'on formalise la suite du process (peut-être en lien avec la "prospection")

**Comment by Morendil** [comment]
Je ferme pour les raisons évoquées sur #366.
