### ISSUE TITLE
Mettre en avant l'aspect "maturation du service"

### ISSUE THREAD

**Issue by Flightan** [sgmap/beta.gouv.fr#369]
La dimension "maturation du service" n'est pas évidente. Ca pourrait être sympa comme ça :
<img width="597" alt="screen shot 2016-10-25 at 14 46 00" src="https://cloud.githubusercontent.com/assets/1177762/19682187/c15323de-9aac-11e6-8277-46270101f8cc.png">

**Comment by Morendil** [comment]
Je ferme pour les raisons évoquées sur #366.
