### ISSUE TITLE
Problème affichage de la légende sur le graph de la page communauté

### ISSUE THREAD

**Issue by l-vincent-l** [sgmap/beta.gouv.fr#371]
Sur linux, sur les navigateurs chromium 53.0.2785.143, et firefox 49.0, il est très difficile, voire impossible, de faire apparaitre la légende du graph sur la page communauté.

**Comment by Morendil** [comment]
A vrai dire c'est pas terrible non plus sur Chrome/Mac.

**Comment by Morendil** [comment]
Ce qui se passe apparemment, c'est que les tooltips/hover ne marchent que sur les x qui contiennent effectivement des données: sur toutes les plages "plates" du graphique le mouseover est sans effet. Quand on positionne le curseur sur une partie du graphe où le niveau change (pour l'une quelconque des 4 catégories) on voit le tooltip s'afficher.

**Comment by MattiSG** [comment]
Si j'ai bien compris, le problème n'est pas lié à Linux, mais simplement au fait que le hover ne fonctionne que sur les points de données, pas sur les lignes de jonction, comme le disait @Morendil.

Il faut peut-être regarder le mode `nearest` : https://github.com/chartjs/Chart.js/pull/3400.

Sinon, comme le suggérait @Morendil :

> le plus simple serait de générer tous les points intermédiaires, un pour chaque jour (ou pour chaque semaine) mais c’est un peu de boulot

…mais ça me semble (h)overkill, franchement.

**Comment by Morendil** [comment]
@MattiSG Oui cette PR dans Chart.js a l'air intéressante. Par contre pour tester il faut installer la version en dév, et après pas mal de temps perdu à essayer de convaincre npm et gulp de se mettre à mon service, j'abandonne ça à plus js-whisperer que moi.

**Comment by MattiSG** [comment]
On peut attendre la publication, ça l'air d'être prévu pour la 2.4  :)

**Comment by MattiSG** [comment]
[v2.4 publiée](https://github.com/chartjs/Chart.js/releases/tag/v2.4.0).

**Comment by Morendil** [comment]
Pas rassuré par un bref essai:

- ça marche un peu mieux avec les anciens modes "dépréciés"
- je n'arrive à rien tirer des nouveaux modes
- la hauteur du canvas est multipliée par 2 et c'est assez vilain

**Comment by Morendil** [comment]
Plus précisément, il y a un bug dans la 2.4.0: quand la hauteur du `canvas` est déterminée par CSS, [cette ligne](https://github.com/chartjs/Chart.js/blob/152ce9c9f83e3678aee663ee250d7cda06bb3b99/src/core/core.controller.js#L73) prévoit de l'ignorer et calculer à la place une hauteur déterminée par la valeur `aspectRatio`spécifiée dans la config.

**Comment by Morendil** [comment]
![LOL](http://recordit.co/C6CQg6gH0l)

**Comment by MattiSG** [comment]
Merci @Morendil, bon boulot d'ouverture de bug sur Chart.js !

**Comment by simonbrunel** [comment]
Chart.js ne permet pas d'affecter des dimensions relatives (%, vw, vh) **directement** sur le canvas car il n'est pas possible (ou bien très bancale) de détecter lorsque la taille du canvas change. La solution est d'ajouter une `div` autour du `canvas` (je n'ai pas pu tester, problème de certificat lors de `bundle install`), mais le code devrait ressembler à çà:

[communaute.html#L37](https://github.com/sgmap/beta.gouv.fr/blob/e2dd50c17ec7be734805146fcdd749189d09fb28/communaute.html#L37)
```javascript
<section id="effectifs" class="ui container">
	<h2 class="ui divider horizontal">Évolution des effectifs</h2>
	<div class="chart-wrapper">
                <canvas>...</canvas>
        </div>
	<p>...</p>
</section>
```

[communaute.css#L1](https://github.com/sgmap/beta.gouv.fr/blob/e2dd50c17ec7be734805146fcdd749189d09fb28/css/communaute.css#L1)
```css
#effectifs .chart-wrapper {
    position: relative;
    height: 60vh;
}
```

**Comment by MattiSG** [comment]
Top, merci @simonbrunel !!

Gênant le problème de certificat, il faut qu'on investigue ça, tu aurais du pouvoir contribuer plus facilement  😞

**Comment by Morendil** [comment]
Ca marche beaucoup mieux, PR en route.

**Comment by simonbrunel** [comment]
@Morendil parfait, n'oubliez pas de fermer les tickets sur le repo de Chart.js :)
