### ISSUE TITLE
Styler les fiches détaillées

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#38]

**Comment by Flightan** [comment]
J'ai essayé de garder l'esthétique carte pour voir ce que cela donne.
WDYT ?

Avant:
<img width="717" alt="screen shot 2016-07-26 at 17 03 13" src="https://cloud.githubusercontent.com/assets/1475946/17143275/2ac8c70c-5353-11e6-8a1c-d8d339f0787d.png">

Après:
<img width="717" alt="screen shot 2016-07-26 at 17 03 43" src="https://cloud.githubusercontent.com/assets/1475946/17143277/2b622050-5353-11e6-9ce3-16b32fdff32e.png">

**Comment by MattiSG** [comment]
J'aime bien l'idée d'agrandir la carte. En revanche, la capture d'écran, le _mission statement_ et le texte sont pour moi les objets principaux de cette fiche détaillée. Je trouve dommage que ce soit les éléments diminués (par la taille ou la couleur).

**Comment by Flightan** [comment]
Ok, on itère sur une PR alors !
