### ISSUE TITLE
Améliorer la lisibilité des articles

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#383]
- [ ] Changer la police.
- [ ] Augmenter l'interlignage.
- [ ] Éclaircir la couleur de fond.
- [ ] Agrandir l'espace avant le footer.

**Comment by Flightan** [comment]
On pourrait trouver un moyen de mettre dans l'en-tête:

- [ ] L'auteur, relié à sa fiche sur la page communauté
- [ ] La startup, reliée à sa fiche sur la page portefeuille

**Comment by MattiSG** [comment]
La startup est actuellement dans l'en-tête (cf. #356) et l'auteur en bas de l'article (cf. #379).
