### ISSUE TITLE
Problème de certificat au `bundle install`

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#435]
D'après @simonbrunel dans #371 :

> problème de certificat lors de `bundle install`

L'autodétection des versions fonctionne-t-elle toujours correctement ? La valeur ajoutée est-elle suffisante pour continuer à utiliser ce système ?

**Comment by Morendil** [comment]
Est-ce que c'est ce problème @simonbrunel ? http://stackoverflow.com/questions/10246023/bundle-install-fails-with-ssl-certificate-verification-error

**Comment by Morendil** [comment]
@MattiSG tu vas peut-être un peu vite en associant ce souci de certificat (lié à la présence d'un Gemfile quel qu'il soit) et le suivi des versions de Github Pages en prod (lié à notre Gemfile très spécifique), j'ai envie d'investiguer un peu plus...

**Comment by simonbrunel** [comment]
Voici le log:

```bundle install

    Something went wrong trying to parse production versions.
    Please report the incident at https://github.com/sgmap/beta.gouv.fr/issues:

      Exception name:    OpenSSL::SSL::SSLError
      Exception message: SSL_connect returned=1 errno=0 state=SSLv3 read server
certificate B: certificate verify failed

Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using i18n 0.7.0
Installing json 1.8.3 with native extensions
Using minitest 5.10.1
Using thread_safe 0.3.5
Using public_suffix 2.0.4
Using coffee-script-source 1.11.1
Using execjs 2.7.0
Using colorator 1.1.0
Using colored 1.2
Using ffi 1.9.14
Using multipart-post 2.0.0
Using forwardable-extended 2.6.0
Using gemoji 2.1.0
Using net-dns 0.8.0
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using kramdown 1.11.1
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using mini_portile2 2.1.0
Using jekyll-paginate 1.1.0
Using jekyll-swiss 0.4.0
Using minima 2.0.0
Using unicode-display_width 1.1.2
Using parallel 1.10.0
Using yell 2.0.7
Installing oj 2.18.0 with native extensions
Using trollop 2.1.2
Using bundler 1.13.6
Gem::InstallError: The 'json' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
```

Le but initial n'étant pas de soumettre une PR, mais de proposer une solution au problème rencontré avec Chart.js, je n'ai pas pris le temps de chercher plus loin.

**Comment by Morendil** [comment]
@simonbrunel ça ressemble au problème cité dans cette issue, ils recommandent de mettre à jour rubygems:

`gem update --system --source http://rubygems.org/`

Si tu as Docker pour Mac, tu peux faire tourner notre site avec ce one-liner

`docker run --rm -it -v (pwd):/app -p 4000:4000 morendil/github-pages`

Sinon pour faire une copie en local:

    wget -mpck --user-agent="" -e robots=off -E https://beta.gouv.fr
    open beta.gouv.fr/communaute.html

**Comment by simonbrunel** [comment]
J'ai déjà tenté de mettre à jour rubygems, sans succès. Ne vous casser pas la tête pour ce problème de certificat si c'est uniquement avec ma config, j'ai posté le code en question dans [ce commentaire](/sgmap/beta.gouv.fr/issues/371#issuecomment-266712166), j'imagine que l'un de vous pourra en faire une PR après l'avoir tester.

**Comment by MattiSG** [comment]
> Ne vous casser pas la tête pour ce problème de certificat si c'est uniquement avec ma config

Ben, ça nous intéresse de permettre la contribution ! Mais ça n'est effectivement pas bloquant pour #371  :)
Merci pour le log !

@Morendil Et pourquoi ne serait-ce pas lié à :

> `Gem::InstallError: The 'json' native gem requires installed build tools.`

?

- - - - -

> tu vas peut-être un peu vite en associant ce souci de certificat et le suivi des versions de Github Pages en prod

J'ai posé des questions pour émettre des hypothèses, pas pour affirmer une causalité  😉

**Comment by Morendil** [comment]
@MattiSG le problème de certificat n'est pas bloquant dans ce cas précis, il fait tomber dans la clause `rescue`, par contre effectivement la gem `json` est nécessaire seulement pour le parsing des dépendances de Github Pages et on pourrait s'en passer en mettant en place un hébergement alternatif.

On pourrait faciliter la contribution concernant le code "front end" (JS et CSS) en mettant à disposition une archive complète du site statique.

Pour faciliter la contribution plus généralement, je pense comme toi que l'alternative de ne plus dépendre de Github Pages se renforce de jour en jour, mais je ne suis pas certain à 100% que le bug dont on parle ici ne se serait pas présenté.

**Comment by MattiSG** [comment]
> faciliter la contribution concernant le code "front end" (JS et CSS) en mettant à disposition une archive complète du site statique.

Bof. Comment proposer les modifications ensuite ?

**Comment by Morendil** [comment]
Je ferme pour l'instant, pour les raisons suivantes:

- d'après le log posté par Simon il y avait au moins deux erreurs, "native gem requires installed build tools" et "certificate B: certificate verify failed"
- il semble qu'il existe des [solutions](http://railsapps.github.io/openssl-certificate-verify-failed.html) en agissant sur la configuration locale de l'utilisateur, mais Simon n'est pas disposé pour l'instant à nous servir de cobaye à ce sujet ;)
- le problème est accessoire à celui plus général de continuer à utiliser Github Pages ou pas
