### ISSUE TITLE
Florian est tout cassé

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/beta.gouv.fr#451]
L'image et le lien sont cassé
Lien : https://beta.gouv.fr/communaute#florian.delezenne
![image](https://cloud.githubusercontent.com/assets/5861569/21847970/b56ca976-d852-11e6-8155-194c7b3d5039.png)

**Comment by Flightan** [comment]
C"est pas Florian c'est [gravatar](http://en.gravatar.com/) qui plante régulièrement.
