### ISSUE TITLE
Affichage des compteurs pas systématique sous CH55

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/beta.gouv.fr#469]
<img width="1150" alt="capture d ecran 2017-01-22 a 10 39 38" src="https://cloud.githubusercontent.com/assets/1231232/22181549/30fd1f8c-e08f-11e6-89f5-119748d6bfd4.png">

Navigateur : Chrome 55
OS : macOS Sierra

Quelqu'un peut essayer de reproduire sur un poste équivalent ?

**Comment by jdesboeufs** [comment]
Je laisse ouvert mais j'ai des problèmes avec d'autres sites.
Donc c'est soit lié à Chrome soit à ma machine en particulier.

**Comment by MattiSG** [comment]
Je ne reproduis pas sous Chrome/Sierra, ni sous Safari/Sierra.

Je pense que tu as un souci avec les polices, car la capture montre une police fallback. Pour info, la famille de polices est `"Century Gothic", "Gilles Sans", "Open Sans", "Helvetica Neue", "Arial"`. Tu devrais pouvoir diagnostiquer l'état des polices avec l'application Livre des polices.

Je ferme pour l'instant. N'hésite pas à rouvrir si tu reproduis à nouveau uniquement sur beta.gouv.fr.
