### ISSUE TITLE
Utiliser l'attribut alt plutôt que title sur les balises img

### ISSUE THREAD

**Issue by Flightan** [sgmap/beta.gouv.fr#473]
Lors de l'affichage des screenshots, nous remplissons l'attribut `title` et pas `alt`. Il semble que de nombreux tests automatisés n'aiment pas cela. Est-ce qu'on a une raison pour mettre l'un plutôt que l'autre ?

https://github.com/sgmap/beta.gouv.fr/blob/master/_includes/screenshot.html#L3

**Comment by MattiSG** [comment]
`title` est lu autant qu'un `alt` par la plupart des lecteurs d'écrans, et affiche en plus une infobulle. D'un point de vue strictement standard, effectivement, c'est moins bien.

Ok pour changer, je ne pense pas à l'usage que l'infobulle apporte de la valeur.

**Comment by Morendil** [comment]
Apparemment le RGAAV3 impose que les attributs `alt` et `title` soient identiques lorsque l'un ou l'autre est renseigné.
