### ISSUE TITLE
Améliorer le taux de contraste sur le texte

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#474]
Le taux de contraste devrait être supérieur à 3:1.

**Comment by Morendil** [comment]
A l'inspection avec [l'outil](http://wave.webaim.org/report#/beta.gouv.fr) de WebAIM il y a des niveaux de contraste insatisfaisants dans la frise notamment: les cases avec les classes "investigation", "success", "retirement" sont (bien) en-dessous de 3:1. On peut aussi avoir un rapport plus détaillé avec [CheckMyColors](http://www.checkmycolours.com/).

On pourrait investiguer l'ajout de ces outils à nos tests auto, dans un deuxième temps...

N.B.: le RGAA mentionne deux niveaux de contraste, 4,5:1 et 3:1 selon les cas. En faisant tourner l'extension Firefox Opquast qui vérifie les règles RGAA V3 je n'ai pas vu d'erreurs sur le taux de contraste, je ne sais pas si c'est dû à une différence entre Opquast et Asqatasun.
