### ISSUE TITLE
Supprimer les <a> vides

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#475]
Certaines pages peuvent apparemment avoir des `<a>` vides.

Cela n'a aucun impact réel d'accessibilité mais diminue le score sur les outils automatisés utilisés par certains benchmarks.

**Comment by Morendil** [comment]
J'ai fait tourner en local asqatasun, l'outil utilisé par Antoine Cao pour l"un de ces audits. (Via docker, donc on pourrait aussi le déployer sur incubateur.net éventuellement pour nos propres audits automatisés dans https://verif.site).

Malheureusement ça ne m'a pas permis d'accéder à une info plus précise sur la localisation dans le DOM ou dans le texte des balises en erreur, l'outil n'a pas prévu ce niveau de détail :(

A la lecture de la règle du diagnostic, je suppose qu'il s'agit des liens qui englobent les screenshots des startups dans le carousel de la page d'accueil; la structure est donc une balise `img` sans texte dans une balise `a`.

Est-ce que fournir une balise `div` ou `span` en plus de l'image, stylée avec `display:none` serait satisfaisant?

**Comment by MattiSG** [comment]
Oui, un `span`, pas un `div`. Il ne faut pas mettre un `display:none` (qui ne serait pas lu non plus par un lecteur d'écran), mais l'équivalent d'une classe “[screenreader only](https://gist.github.com/mzabriskie/020e22edbb9119d41872)”. Il faut voir ce que SemanticUI fournit en natif à ce sujet.

**Comment by Morendil** [comment]
> ce que SemanticUI fournit en natif à ce sujet

[Apparemment](http://stackoverflow.com/questions/39982221/what-is-the-semantic-ui-equivalent-of-bootstraps-sr-only) rien.
