### ISSUE TITLE
Mettre à jour la description de OGPtoolbox

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#518]
Il semblerait que la passation soit terminée, et que le projet soit repris par la société civile.

@pfa86 pourrais-tu [mettre à jour](https://github.com/sgmap/beta.gouv.fr/edit/master/_startup/ogptoolbox.md) la fiche d'OGPtoolbox en conséquence ?  😃 À ta dispo pour toute question !

**Comment by Morendil** [comment]
Salut @pfa86, afin que le site reflète la réalité, je vais passer le statut du produit à "reprise", et fermer cette issue; n'hésite pas à [mettre à jour](https://github.com/sgmap/beta.gouv.fr/edit/master/_startup/ogptoolbox.md) la fiche quand tu auras les éléments.
