### ISSUE TITLE
Mettre à jour les dates de contrat pour les portages multiples

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#524]
Depuis l'intégration de #517, il est devenu possible de déclarer un historique de rattachements.

Il faudrait donc mettre à jour les métadonnées `contracts` de :

- [ ] @fpagnoux.
- [x] @monbocal

**Comment by jdesboeufs** [comment]
J'ai corrigé mon historique dans #527 !

**Comment by Morendil** [comment]
@monbocal via #530
