### ISSUE TITLE
Distinction communauté / ancien·ne·s HS

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/beta.gouv.fr#528]
Depuis l'évolution du modèle de données, la distinction n'est plus opérante.

<img width="912" alt="capture d ecran 2017-03-05 a 19 53 50" src="https://cloud.githubusercontent.com/assets/1231232/23590307/75d808f0-01dd-11e7-86b7-f024cc61a72f.png">

**Comment by Morendil** [comment]
Oops.
