### ISSUE TITLE
Lien "annonces" en 404

### ISSUE THREAD

**Issue by MathRobin** [sgmap/beta.gouv.fr#544]
Dans https://github.com/sgmap/beta.gouv.fr/pull/534, vous avez renommé "Annonces" en "Blog". Mais il y a des anciens liens qui du coup ne marchent plus.

https://beta.gouv.fr/annonces -> Erreur 404

Peut-on envisager qu'une redirection en 301 soit mise en  place ?

**Comment by Morendil** [comment]
En cours: #545 

Merci pour le signalement :)
