### ISSUE TITLE
Simplifier la représentation des contrats

### ISSUE THREAD

**Issue by Morendil** [sgmap/beta.gouv.fr#548]
Avec #517 on a dépassé les limites de Jekyll dans sa configuration standard sur Github Pages: la modélisation "fine" des rattachements des membres de la communauté s'avère incompatible avec la méthode simple pour trier les fiches par ordre inverse d'arrivée, Jekyll n'étant pas capable d'opérer un tri sur une propriété d'un sous-objet (e.g. `sort: contracts.last.start`).

Pour éviter cet "overkill":
- [ ] Le graphe devient monochrome (pas d'historique des rattachements)
- [ ] La répartition _actuelle_ des rattachements est affichée en annexe
- [ ] On revient à la situation avant #517 - chaque membre a un seul `start` et `end`

(Une alternative existe: en sortant de l'hébergement sur Github Pages, on pourrait implémenter un filtre custom `sort_by_exp`, évitant ainsi les contorsions de #541)

**Comment by Flightan** [comment]
Je trouve également que la notion de contrat avec date de début et fin est en fait peut-être trop compliquée et risque de limiter la participation.

Je suis OK avec la solution proposée de rollback.

Je ne sais pas si c'est exactement le même problème pour le graphe des effectifs, le problème étant qu'on affiche un historique qui est modifié au rythme des affiliations de chacun.
On peut effectivement contourner ce défaut ainsi:
![effectifs](https://cloud.githubusercontent.com/assets/1475946/23744255/cc42bfa4-04b3-11e7-9859-8028cde164e4.jpg)

**Comment by MattiSG** [comment]
Il y a un mélange entre plusieurs problèmes…

Si on rollback #517, on a de nouveau un graphe de croissance qui est faux (qui était le problème initial que ce changement devait corriger), et pas besoin de rendre la représentation monochrome.

La difficulté technique est uniquement liée au tri (cf. #541).

@Flightan apporte encore un autre souci sur la difficulté de contribution, qui ne me semble pas insurmontable (car il n'y a quasiment que l'indentation qui change pour un nouvel entrant) et qui me semble être apparu surtout par coïncidence avec #438.

Sortir du rendu Jekyll de GitHub Pages ne signifie pas nécessairement sortir de GitHub Pages. On peut compiler le site en CI (c'est déjà le cas) et uploader le résultat sur une branche dédiée de ce dépôt (par exemple avec un équivalent de [`tschaub/gh-pages`](https://github.com/tschaub/gh-pages)).

**Comment by ppezziardi** [comment]
@MattiSG je ne comprends pas ta proposition. Pourquoi ne fait-on pas la solution @Flightan ? beta.gouv n'est pas un ERP RH, c'est un outil pour générer du lead entrant, que ce soit des affaires ou des recrutements. Et je suis très ennuyé par la régression du tri par dernier arrivant qui dure depuis maintenant plusieurs semaines ... 
my2c.

**Comment by MattiSG** [comment]
> Pourquoi ne fait-on pas la solution @Flightan ?

Parce que ça ne résolvait pas le problème du tri.
