### ISSUE TITLE
Simplifier la page contact 

### ISSUE THREAD

**Issue by elizlp** [sgmap/beta.gouv.fr#550]
La page contact contient beaucoup de texte et on a du mal à trouver les vrais liens contact (le lien email est tout en bas et peu visible, il se fond dans le paragraphe ...) 

:)

**Comment by Morendil** [comment]
Bonjour @elizlp, c'est en partie délibéré: la finalité du site est de créer des mises en relation entre l'incubateur et des profils qualifiés - on préfère que les publics de cette page se "trient" plutôt que faire converger tout le monde vers un seul lien de contact.

Question sincère: est-ce que tu avais repéré qu'il y a plusieurs liens mailto dans la page, chacun avec un sujet de mail différent ? Si ce n'est pas le cas, ça peut être pertinent de les signaler, par exemple avec un picto "enveloppe".

**Comment by MattiSG** [comment]
Pour moi c'est une feature  🙂
