### ISSUE TITLE
La traduction de « Startup d'État » comme "State Startup" semble bizarre

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/beta.gouv.fr#590]
Si l'on pouvait trouver la racine de l'expression –délibérément paradoxale– « Startup d'État » dans « Entreprise d'État », sa traduction adequate serait, en anglais, "State chartered and owned Startup", voire "State Startup". Or, cela impliquerait l'existence juridique d'une startup d'État, ce qui n'est pas vrai, car « une startup d'État n'est pas une startup ». Idées ?

**Comment by Morendil** [comment]
The best way to resolve this, ISTM, is to engage native speakers in conversation about our translation. To do so, I'd merge #564 and tweet the new About page, requesting comments about the translation specifically.

**Comment by MattiSG** [comment]
Je ne comprends pas le problème que tu décris.

> cela impliquerait l'existence juridique d'une startup d'État

À mon sens au moins autant que Startup d'État, et c'est ce paradoxe qu'il faut toujours expliquer immédiatement.

**Comment by Morendil** [comment]
Cf. https://twitter.com/Morendil/status/846289663660883968

**Comment by Morendil** [comment]
Alternative suggérée par @cquest : "Gov Startup"

**Comment by maukoquiroga** [comment]
> À mon sens au moins autant que Startup d'État, et c'est ce paradoxe qu'il faut toujours expliquer immédiatement.

J'ai l'impression qu'en anglais ce jeu sémantique ne marche pas trop (et c'est normal, l'on ne traduit pas le mode de fonctionnement d'un gouvernement ni ses raccourcis symboliques).

J'avais pensé à "Public Startup", mais dans le contexte du R.-U. cela pourrait encore dénoter une délégation de service public vers une « petite pousse » privée. En ce qui concerne les É.-U., je n'en ai aucune idée.

"Gov Startup" semble pertinent, mais attendons à avoir plus de feed-back des native speakers, il faut bien valider que ma question est pertinente/correcte avant d'opérer un changement quelconque.

**Comment by Morendil** [comment]
Après la discussion sur Twitter, mon sentiment est que la traduction "State Startup" ne pose pas _plus_ problème que l'expression "Startup d'État": elle possède les mêmes connotations et exige les mêmes explications.

Par ailleurs, elle a [déjà](http://blogs.ec.europa.eu/promotingenterprise/france-learns-from-startup-companies-in-modernising-public-online-services/) été diffusée [précédemment](https://www.slideshare.net/AgileLietuva/matti-schneider-how-public-action-gets-digital) apparemment sans soulever de problème.

Je propose de fermer et de réouvrir si lors de discussions avec des anglophones (par exemple les contacts à venir lors de conférences internationales) une alternative clairement préférable émerge.

**Comment by MattiSG** [comment]
Merci, je confirme que ça fait [2 ans](https://www.youtube.com/watch?v=mogQRJaf1tI&feature=youtu.be&t=52s) que je teste la traduction et que j'ai des réactions totalement similaires pour les anglophones que celles des francophones face à Startup d'État :wink:
