### ISSUE TITLE
Envoyer une newsletter interne avec les 🚀

### ISSUE THREAD

**Issue by kemenaran** [sgmap/beta.gouv.fr#612]
_Discuté au Grand Séminaire_

On pourrait compiler régulièrement les messages "🚀" de Slack, et les envoyer dans une newsletter interne, mensuelle ou bi-mensuelle. Ça peut même s'automatiser.

**Comment by kemenaran** [comment]
@l-vincent-l pendant le séminaire tu avais proposé de prendre ça en charge ?

**Comment by l-vincent-l** [comment]
Yep.
Je prends.

**Comment by Morendil** [comment]
On a fait un point là-dessus avec @kemenaran (en direct du ministère).

Les questions qui se posent sont:
 - [ ] qu'est-ce qu'on automatise et qu'est-ce qu'on fait à la main
 - [ ] comment on récupère les messages
 - [ ] comment on éditorialise (éventuellement) la matière brute
 - [ ] comment on met en forme
 - [ ] où on publie le résultat

Le plus simple c'est d'avoir un script qu'on déclenche à la main, en plus sophistiqué on peut imaginer une commande Slack.

On a fait un essai en passant par https://api.slack.com/methods/search.messages/test

Il faut générer un token, à partir de là on récupère un JSON. On peut faire de la mise en forme avec `jq`? Ou un truc en Node ou en Ruby?

On peut éventuellement s'appuyer sur Trello pour éditorialiser au niveau de chaque item, ou alors on peut dumper toute la recherche (un peu mise en forme) dans un GDoc avec accès "open bar" ou dans un Framapad public.

Au final on poste l'URL du truc dans Slack ou on l'envoie par mail.

**Comment by kemenaran** [comment]
> Au final on poste l'URL du truc dans Slack ou on l'envoie par mail.

Ça me semble intéressant d'avoir une temporalité différente entre les rocket au jour le jour, et le résumé bi-mensuel.

Quelque part les gens sur Slack sont déjà au courant des `rocket` au quotidien. Alors que si on envoie le résumé par email, ça permet justement aux gens un peu moins le nez dans le guidon de se tenir au courant malgré tout.

**Comment by maukoquiroga** [comment]
Salut @l-vincent-l, c'est encore toi qui es là-dessus ?

**Comment by Morendil** [comment]
Plus d'activité sur ce sujet, et le consensus sur l'usage de :rocket: pour annoncer des avancées n'est plus de mise sur Slack à l'heure actuelle (l'emoji est en particulier utilisé dans le canal #startup-aideanah-err), au profit de #incubateur-kifs.
