### ISSUE TITLE
Créer des teams Github par compétence

### ISSUE THREAD

**Issue by kemenaran** [sgmap/beta.gouv.fr#613]
_Discuté pendant le Grand Séminaire_

Pour améliorer la communication entre startups, et faciliter l'entraide et le partage de bonnes pratiques, on s'est dit que ça serait utile de pouvoir mentionner des teams techniques comme `@rubyistes` ou `@pythonistas` dans les issues ou les PR.

Pour ça on peut créer des teams Github mentionnables par domaine de compétence.

**Comment by kemenaran** [comment]
@fpagnoux @Flightan l'un de vous deux avait proposé de prendre ça en charge, je crois ?

**Comment by Morendil** [comment]
Hmmm ça pourrait bien matcher avec une idée qu'on pense prendre avec @l-vincent-l qui consiste à augmenter https://github.com/sgmap/BetaGouvBot d'une feature qui va automatiquement ajouter à l'orga SGMAP les comptes Github des membres qui crééent leur fiche sur beta.gouv.fr. Dans la foulée on peut aussi les inscrire à la team de leur startup et pourquoi pas à des teams correspondant à des tags qui identifient leurs compétences.

**Comment by MattiSG** [comment]
C'était @Flightan :whistle:

**Comment by maukoquiroga** [comment]
C'est, a-t-on des nouvelles ? As-tu besoin d'aide @Flightan ?

**Comment by Flightan** [comment]
@sgmap/javascript ceci est un test

**Comment by oncletom** [comment]
Pas mal en effet si c'est combiné avec https://github.com/blog/2392-introducing-code-owners pour attribuer des code reviews automatiquement.

**Comment by maukoquiroga** [comment]
@oncletom Je ne suis pas forcement hyper fan ni du concept de code owner, car on devrait toujours coder de manière à que le code soit directement collectivisable, ni de l'attribution automatique des code reviews, car push === !flow efficiency, cf kanban.

**Comment by oncletom** [comment]
Je rejoins tes deux avis — sur la notion d'owner et de push/pull.

J'avais tendance à traduire/détourner le mécanisme de _code owners_ par _référents de domaine technique_.

**Comment by maukoquiroga** [comment]
TODO:

- [x] [Create spreadsheet](https://docs.google.com/spreadsheets/d/113XJiJ3Tpz7wlQY3gqA3eqTQR-m0ClOtqoQSUQ8iiwk/edit#gid=0)
- [x] Publish in Slack
- [ ] Create all teams
- [ ] Document in wiki how to 
  a) add teams to a project, 
  b) add himself/herself to a team and 
  c) ask for review to a team.

**Comment by Flightan** [comment]
> - [ ] Create all teams

Je n'ai pas de liste exhaustive des teams donc je ne sais pas comment savoir que c'est job done.

**Comment by maukoquiroga** [comment]
@Flightan On va devoir le faire progressivement, non ? Si la feature est bien documenté dans le wiki, on pourrait s'attend à que les gens demandent au cas par cas d'être ajouté·e·s aux teams.

**Comment by MattiSG** [comment]
Oui. Il faut juste ajouter un paragraphe pour expliquer comment utiliser l'autocomplétion pour rechercher un groupe de pratique, et demander sur `#incubateur-secretaria` à en créer / se faire ajouter s'il en manque. :shipit: !

**Comment by maukoquiroga** [comment]
https://github.com/sgmap/beta.gouv.fr/wiki/Demande-d%27aide-au-collectif
