### ISSUE TITLE
Mettre en avant le wiki pour les nouveaux

### ISSUE THREAD

**Issue by kemenaran** [sgmap/beta.gouv.fr#614]
_Discuté lors du Grand Séminaire_

Aujourd'hui certaines pages du wiki ne sont pas visibles ou connues, notamment par les nouveaux arrivants.

Pour arranger ça on pourrait rajouter à la page [[Bienvenue]] une section "Pour la suite", avec quelques pages de wiki intéressantes à consulter quand on rejoint l'incubateur.

**Comment by Morendil** [comment]
Implémentation alternative: un Slackbot qui signale les pages intéressantes, on rejoindrait la proposition évoquée sur https://github.com/sgmap/beta.wip/wiki/Id%C3%A9es-transverses-folles et on peut réutiliser https://github.com/18F/dolores-landingham-slack-bot

**Comment by maukoquiroga** [comment]
Ce n'est pas une mauvaise idée @Morendil. De toute façon, je commencerais pour le journey mapping : et si l'on fait du shadowing avec un·e nouveaux·elle ? Comme ça nous pourrons prioritiser les contenus suivant une logique de progressive disclosure, editorialiser le wiki et, éventuellement, créer notre propre bot « Laurent Botsavit »

**Comment by Morendil** [comment]
On a un peu plus de maîtrise qu'il y a un mois sur l'implémentation de bots, et peut-être un peu de recul pour revisiter cette issue. L'idée du bot est peut-être overkill et une simple liste dans la page Bienvenue tel que suggéré à l'origine peut être suffisant.

Questions:
 - [ ] Quelle est *la* page que les nouveaux ont le plus de mal à repérer ?
 - [ ] Quel est le bon moment pour leur donner l'info ?

**Comment by Morendil** [comment]
Pas d'activité et pas de réelle demande de la part des nouveaux à ce sujet précis. D'autres améliorations sur l'onboarding sont peut-être à recensers mais celle-ci n'est plus d'actualité.
