### ISSUE TITLE
Pas possible d'« ajouter un membre à l'équipe Incubateur  en un clic par l'interface web de GitHub 😃 »

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/beta.gouv.fr#636]
D'après le [wiki](https://github.com/sgmap/beta.gouv.fr/blob/master/CONTRIBUTING.md#ajouter-un-membre-%C3%A0-l%C3%A9quipe-incubateur), on peut « ajouter un membre à l'équipe Incubateur  en un clic par l'interface web de GitHub 😃 ».

Mais ce n'est pas vrai, parce que :

- Si la personne n'a pas push rights, impossible de téléverser une image
- Sans image, CircleCI pête

What is to be done ?

**Comment by Morendil** [comment]
J'ai créé un compte (hi @Lidnerom) pour comprendre ce qui se passe. Une fois ce compte ajouté à l'organisation SGMAP, si je suis le lien "ajouter un membre", je vois un message "You need to fork this repository to propose changes." et un bouton qui va créer un fork pour moi.

J'ai créé mon fork mais je ne suis pas allé au bout de la démarche (en ajoutant une image), je voudrais d'abord savoir si c'est ce qui s'est passé pour @AlexiaR ou pour d'autres personnes. Il me semble que sur un fork, chacun a les droits de faire ce qu'il ou elle veut, y compris remonter des images. Le problème est peut-être plutôt dans un manque d'explications pour le faire comme il faut.

**Comment by Morendil** [comment]
Pour respecter la promesse "en un clic", je reconnais qu'on pourrait peut-être changer le code, de sorte qu'un nouveau membre a seulement besoin de créer sa fiche, sans que l'ajout d'un avatar soit obligatoire. Mais on souhaite quand même encourager fortement l'ajout des avatars, et minimiser le nombre d'apparitions de l'image par défaut "tube à essai".

**Comment by maukoquiroga** [comment]
> Pour respecter la promesse "en un clic", je reconnais qu'on pourrait peut-être changer le code, de sorte qu'un nouveau membre a seulement besoin de créer sa fiche, sans que l'ajout d'un avatar soit obligatoire.

Avant de le rendre pas obligatoire, une idée : testons une rédaction qui mette l'accent plutôt sur "lien https vers une image" que dans l'upload.

**Comment by Morendil** [comment]
Une version plus radicale de cette idée: déportons la gestion des avatars vers Github, en nous appuyant sur [Jekyll-Avatar](https://github.com/benbalter/jekyll-avatar).
