### ISSUE TITLE
Expérimenter un outil pour mieux gérer les mailing-lists internes

### ISSUE THREAD

**Issue by kemenaran** [sgmap/beta.gouv.fr#647]
Aujourd'hui les différentes _"mailing-lists"_ (internes ou externes) sont gérées par des redirections OVH vers les adresses email des personnes concernées.

### Douleurs

- Les messages de répondeur automatique (_"je suis absent cette semaine"_) sont envoyés à toute la mailing-list ;
- L'historique d'une discussion en cours n'est pas consultable facilement ;
- Les archives ne sont pas consultables facilement ;
- Pas de moyen facile de dire _"je prends ce message"_ ;
- Pas de verrouillage des mailing-lists à usage internes (n'importe qui d'externe peut poster dessus).

### Usages envisagés

À vue de nez le terme de _"mailing-list"_ regroupe aujourd'hui différent usages.

- Des **listes de diffusion internes**, sur lesquelles seules les membres peuvent poster. Pour se partager de l'information entre nous.
- Des **listes "hotline"**, sur lesquelles tout le monde peut poster (mais seuls les abonnés peuvent voir les archives). Pour gérer les contacts externes, le recrutement, le support, la compta…
- (peut-être aussi des **listes forum**, sur lesquelles tout le monde peut poster et voir les archives)

### Outils à explorer

Pour l'instant on n'a pas d'outil magique qui répondrait à ces besoins. Si ça se trouve, il y a même différents outils pour différents besoin.

Dans les pistes à explorer pour se donner des idées :

- [sympa](http://www.sympa.org/), qui fait de la mailing-list à l'ancienne, mais assez configurable. On peut tester gratuitement sur https://framalistes.org (avec une belle UI claire)

- [OTRS](https://www.otrs.com/), qui est surtout adapté aux listes en contact avec l'extérieur (support, recrutement), et qui permet de s'assigner des emails facilement.

On commence par regarder ceux là, pour se donner des idées, et peut-être expérimenter.

**Comment by kemenaran** [comment]
Au passage, pour se donner du grain à moudre, la liste des types de listes configurables sur Framalistes/sympa :

<img width="800" alt="capture d ecran 2017-04-19 a 18 03 45" src="https://cloud.githubusercontent.com/assets/179923/25189806/9845d3e8-252a-11e7-8ab1-204e789ba2f0.png">

**Comment by kemenaran** [comment]
Dans les autres outils de support / ticketing / contact externe à explorer éventuellement :

- [HelpScout](https://www.helpscout.net/), chaudement recommandé par des gens qui ont fait du support client _(payant)_ ;
- [OsTicket](http://osticket.com/), un genre d'OTRS un peu rugueux, mais en PHP plutôt qu'en Perl _(open-source, auto-hébergé (gratuit) ou cloud (payant))_ ;
- [Zendesk](https://www.zendesk.fr/), pas mal, pas d'enthousiasme démesuré non plus _(payant)_.

**Comment by Morendil** [comment]
@guillett recommande FrontApp

**Comment by guillett** [comment]
Juste en passant pour y faire référence si besoin http://untroubled.org/ezmlm/

**Comment by Morendil** [comment]
Abandonné au profit d'une implémentation via l'API OVH, activable par commande Slack.
