### ISSUE TITLE
Rediriger retraite.beta.gouv.fr vers quelque chose

### ISSUE THREAD

**Issue by teolemon** [sgmap/beta.gouv.fr#671]
http://retraite.beta.gouv.fr est mort.
Est-il possible de rediriger vers le service maturé, ou bien de mettre une page expliquant que le projet est en cours de transfert ?

Vérifier également que ce n'est pas le cas pour d'autres projets.

Je sais bien qu'il y a écrit *bêta* en gros dessus, mais je pense que d'autres font la même chose.

**Comment by maukoquiroga** [comment]
Une idée pour s'assurer que les liens sont toujours d'actualité :

```shell
bundle exec htmlproofer ./_site/startup --checks-to-ignore ImageCheck,ScriptCheck --only-4xx --assume-extension --external_only
```

**Comment by maukoquiroga** [comment]
Superseded by #765
