### ISSUE TITLE
Le rapport annuel PDF est disponible facilement sur le site

### ISSUE THREAD

**Issue by ppezziardi** [sgmap/beta.gouv.fr#675]
PDF à livrer par PP
Je propose de le monter dans le footer, au-dessus de "une mission du SGMAP", avec un lien "Rapport annuel" ou "Qui sommes nous ?"

L'an prochain on évoluera vers "Rapports annuels" et une page intermédiaire avec l'historique.

**Comment by maukoquiroga** [comment]
@ppezziardi Pourquoi un PDF (et pas un blog post par exemple) ?
