### ISSUE TITLE
Documenter le fait qu'il faille renseigner son nom d'utilisateur GitHub dans sa fiche author pour etre ajouté automatiquement au groupe SGMAP

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/beta.gouv.fr#712]

**Comment by Zerhariel** [comment]
IMHO Il serait interessant de linker la documentation à la présentation du groupe SGMAP vu que c'est là qu'on cherche en premier

**Comment by maukoquiroga** [comment]
Est-ce par rapport au bot ? cc @Morendil

**Comment by gregoirenovel** [comment]
Oui : https://github.com/sgmap/betaGouvBot/blob/4909b2ff7af3e6b717c1be160f817de4f09ebd0d/lib/betagouvbot/github_request.rb#L15

**Comment by maukoquiroga** [comment]
Qui prend ? @gregoirenovel @Zerhariel @Morendil ?

**Comment by maukoquiroga** [comment]
Apparemment déjà fait https://github.com/sgmap/beta.gouv.fr/wiki/Bienvenue#github-partie-1 :

> Tu peux lier ton compte GitHub à ta fiche personnelle en incluant une ligne de la forme github: moncompte parmi les données te concernant. Tu seras alors invité automatiquement, dans les 24 h, à rejoindre l'organisation sgmap ; tu peux à ta convenance rendre publique ton appartenance à l'organisation.
