### ISSUE TITLE
Imposer un ratio (voire un format) pour les screenshots des startups

### ISSUE THREAD

**Issue by guillett** [sgmap/beta.gouv.fr#724]
Il y a un problème d'alignement des images dans la liste des startups.

![capture d ecran 2017-05-24 a 13 48 28](https://cloud.githubusercontent.com/assets/1410356/26401765/ba7fe3b8-4087-11e7-84cd-c33142acce5c.png)

**Comment by maukoquiroga** [comment]
Quelqu'un·e travaille ci-dessus ?

**Comment by maukoquiroga** [comment]
Tu prends @guillett ?

**Comment by Morendil** [comment]
Je prends, je vais faire une passe d'harmonisation des formats + optimisation en complément de ce qu'a déjà fait @monbocal + rédaction de guidelines dans CONTRIBUTING
