### ISSUE TITLE
Le lien vers le rapport annuel sur la page "À propos" est cassé

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/beta.gouv.fr#730]
Cf. mail du 30 mai

**Comment by maukoquiroga** [comment]
Fix doesn't seem to be working

**Comment by maukoquiroga** [comment]
https://beta.gouv.fr/debug.txt

**Comment by Morendil** [comment]
Oui, cette valeur de baseurl est incorrecte. Elle devrait être "" ou "/".

**Comment by Morendil** [comment]
J'essaie de comprendre à quel moment, dans la chaîne de traitement, se fait l'insertion de baseurl devant le lien. C'est en tout cas **avant** le rendu du contenu Markdown en HTML.

**Comment by Morendil** [comment]
Le coupable semble être plus précisément le plugin https://github.com/benbalter/jekyll-relative-links

La raison précise pour laquelle le lien vers le rapport dans le footer n'est pas affecté, mais celui dans la page `apropos.md` l'est, c'est que les plugins de ce type ne sont exécutés que sur les documents de contenu (et jekyll-relative-links en particulier [ne traite que les fichiers `.md`](https://github.com/benbalter/jekyll-relative-links/blob/master/lib/jekyll-relative-links/generator.rb#L28)), pas sur les layouts. Les layouts sont traités par une autre chaîne (HTML+Liquid) et [nous avons profité](https://github.com/sgmap/beta.gouv.fr/blob/master/_includes/footer.html#L10) du filtre `markdownify` pour exprimer certaines parties du footer en markdown, mais la chaîne de traitement n'est pas du tout la même pour ces deux liens.

TLDR: tous les autres liens dans les pages de contenu sont potentiellement affectés par ce problème.

Reste la question: pourquoi seulement le lien vers le rapport annuel et pas les autres liens? Tout simplement parce que nous avons pris l'habitude de formuler nos liens sans extensions dans les pages de contenu, par exemple des liens vers `/startups`. Ces liens marchent et nous permettent de ne pas nous soucier de l'extension. Or `jekyll-relative-links` [vérifie](https://github.com/benbalter/jekyll-relative-links/blob/master/lib/jekyll-relative-links/generator.rb#L77), avant d'appliquer la transformation, que la cible du lien fait bien partie des pages du site. Cette comparaison se fait en incluant l'extension. Dans le cas du PDF seul le lien incluant l'extension fonctionne.

Le "fix" qui va bien à mon avis c'est de trouver moyen de désactiver ce plugin, qui compte tenu de notre configuration (valeur de `baseurl`) ne peut pas donner de résultats valables.

**Comment by Morendil** [comment]
Malheureusement la gem github-pages [ne semble pas permettre](https://github.com/github/pages-gem/blob/master/lib/github-pages/configuration.rb#L102) de désactiver un des plugins configurés par défaut.

**Comment by Morendil** [comment]
Un contournement possible serait d'exprimer le lien vers `/rapportannuel.pdf` comme un lien HTML dans le fichier `apropos.md`. On échapperait à la regex utilisée par jekyll-relative-links pour détecter les liens.

**Comment by maukoquiroga** [comment]
Il y a aussi
- #739 (embed)
- ou peut-être tout simplement [file]({{ site.url }}/file.pdf) ?

**Comment by Morendil** [comment]
Encore un autre correctif possible: renseigner baseurl="" dans _config.yml. Malheureusement, un bug déjà signalé, github/pages-gem#350, rend cette solution inopérante aussi.

**Comment by maukoquiroga** [comment]
Fixed by @Morendil (merci d'ajouter la solution en commentaire)

**Comment by Morendil** [comment]
Um, no... not fixed. 😛

**Comment by maukoquiroga** [comment]
I think the issue was with a missing `proxy_redirect` directive in `nginx-shared`.

**Comment by Morendil** [comment]
That was the root cause for #734 but my analysis for #730 was quite different; if the proxy_redirect fix also fixed this, it's a surprise, even if a nice one.

**Comment by Morendil** [comment]
"Bandaid" fix via #731. Not a permanent solution, but enough for now.

**Comment by Morendil** [comment]
I don't see how changing a request rewriting rule can possibly cause a link *inside* the page to be changed. Reopening to investigate.
