### ISSUE TITLE
Interdire l'inclusion d'images non servies en HTTPS

### ISSUE THREAD

**Issue by davidbgk** [sgmap/beta.gouv.fr#74]
Avec Firefox :

<img width="367" alt="capture d ecran 2016-02-25 a 13 29 42" src="https://cloud.githubusercontent.com/assets/3556/13329790/dc9fb98e-dbc3-11e5-81c5-5e43152d269d.png">

Proposition de résolution : rapatrier les images localement.

**Comment by MattiSG** [comment]
@ismael-hery Auriez-vous une version carrée du logo La Bonne Boîte hébergée sur un serveur en HTTPS ?

**Comment by jdesboeufs** [comment]
On peut la mettre dans `img` aussi, ça évitera les liens morts sur le long terme.

**Comment by jdesboeufs** [comment]
Ok j'avais pas lu ta remarque David.

**Comment by MattiSG** [comment]
Possibilité de corriger a minima en intégrant l'image de MPS, en s'inspirant des commits liés ci-dessus (screenshot : 1280x720).

Il faudra pour réellement corriger imposer l'usage de HTTPS (cf. [branche `screenshots`](https://github.com/sgmap/beta.gouv.fr/compare/screenshots?expand=1)).

**Comment by MattiSG** [comment]
@maukoquiroga est-ce que le linter de HTML que tu as mis en place pourrait gérer cette validation (vérifier que toutes les `src` de `<img>` sont en HTTPS) ?

**Comment by maukoquiroga** [comment]
@MattiSG Oui : #253 ! :wrench:
