### ISSUE TITLE
Servir une page 404 à nos couleurs

### ISSUE THREAD

**Issue by Morendil** [sgmap/beta.gouv.fr#742]
On peut faire ça [semble-t-il](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/commands/serve.rb#L64), est-ce que ça vaut le coup ?

**Comment by MattiSG** [comment]
Oui, surtout que l'ajout de slashes ou pas semble faciliter le fait de servir des 404. Exemple : https://beta.gouv.fr/startups/
