### ISSUE TITLE
Le logo n'est pas toujours visible sur le header

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/beta.gouv.fr#749]
- [ ] L'afficher en permanence
- [ ] L'aligner à gauche au lieu de l'aligner à droite (plus conventionnel)
- [ ] Lui rajouter du padding pour que le `hover` soit plus esthétique

**Comment by MattiSG** [comment]
C'était bien un choix volontaire de la part de @Flightan que de ne pas l'afficher en permanence. As-tu vu ce que donnerait la page d'accueil avec le logo répété dans le header ?

**Comment by gregoirenovel** [comment]
Oui, j'aurais du ajouter "et modifier la page d'accueil pour que le logo ne soit visible qu'à un seul endroit : dans la navigation".

La motivation derrière ce changement c'est d'avoir un header qui ne change jamais, ce que je trouve moins perturbant.
