### ISSUE TITLE
Dimensionner l'image associée à la startup correctement quand il n'y a pas de site

### ISSUE THREAD

**Issue by Morendil** [sgmap/beta.gouv.fr#755]
Cf #744 - @guillett c'est bien ça le bug?

**Comment by guillett** [comment]
Le problème est l'absence de lien (plutôt que l'absence de site).

Une analyse complémentaire m'amène à penser que le problème vient de la façon dont les images dans les `card`s sont stylisées par semantic-ui.

Le style qui pollue la vue Ma VAE :
```css
.ui.card > .image > img, .ui.cards > .card > .image > img {
 width: 100%
}
```


DOM pour Ma VAE
```html
<div class="image">
    <img class="screenshot" src="/img/startup/mvmd.jpg" title="Interface de Ma VAE, mon diplôme - MVMD" alt="">
</div>
```



DOM pour MesAides
```html
<div class="image">
    <a href="https://mes-aides.gouv.fr" target="_blank" rel="noopener">
        <img class="screenshot" src="/img/startup/mes-aides.png" title="Interface de Mes Aides" alt="">
    </a>
</div>
```


Je ne sais pas si il y a un bon dimensionnement ou une bonne proportion.

**Comment by Morendil** [comment]
Vu, il faudrait `width: auto` qui est la valeur par défaut. Merci pour l'investigation!
