### ISSUE TITLE
Renommer l'organisation GitHub en BetaGouv

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/beta.gouv.fr#773]
`BetaGouv` ou `betagouv` ou `betagouvfr` ou `beta.gouv.fr` (ma préférence va à ce dernier)

**Comment by Morendil** [comment]
Plutôt favorable **à terme** mais il faut vraiment y aller doucement et planifier cette intervention: on risque de laisser beaucoup de liens cassés et de dégât réputationnel en conséquence.

**Comment by maukoquiroga** [comment]
Ce n'est pas seulement une opération de renommage mais aussi de marketing, politique, etc. Je ferme l'issue pour l'instant.
