### ISSUE TITLE
Créer un flux RSS distinct pour les offres d'emploi

### ISSUE THREAD

**Issue by Morendil** [sgmap/beta.gouv.fr#799]
Est-ce que les bénéfices en valent le coût d'implémentation ?

**Comment by maukoquiroga** [comment]
@Morendil Pour ma part, je ne crois pas, au moins pas encore : le schéma et les métadonnées des offres d’emploi connaissent une évolution rapide, plusieurs offres ont été « splittées », etc. Il faudrait attendre à une stabilisation du format, IMHO.

**Comment by Morendil** [comment]
Réouvrir après stabilisation.
