### ISSUE TITLE
Créer une catégorie "Ancien·ne·s" dans le graphique communauté pour avoir une visibilité sur la communauté active

### ISSUE THREAD

**Issue by HelaG** [sgmap/beta.gouv.fr#827]
Ce graphe nous sert a montrer combien on est.
Pour donner une vision sincère de notre effectif "actif", on pourrait ajouter une catégorie "ancien·ne·s" tout statut confondu.

**Comment by blayo** [comment]
Je ne suis pas certain de comprendre le résultat souhaité : le nombre d'"ancien.ne.s" n'est-il pas en constante augmentation avec le temps ?

(pour être sùr, c'est bien du graphe suivant dont il est question ? )
![graphe-effectifs-incubateur](https://user-images.githubusercontent.com/181349/32084095-7a9d7ec6-bac7-11e7-8c25-c845f818aa09.png)

**Comment by pblayo** [comment]
Est réalisé par #1008 :
![ancien-ne-s](https://user-images.githubusercontent.com/181349/32419916-9313a27e-c282-11e7-8cae-412b2b2deef4.png)

**Comment by HelaG** [comment]
@pblayo comme je te disais hier, je crois que cette issue n'est plus pertinente. Le graphe actuel représente bien la communauté active. Il sert à répondre à la question "combien est-on aujourd'hui ?".

Si tu vois un problème avec la version actuelle du graphe parlons-en, sinon je propose de clore cette issue.

**Comment by pblayo** [comment]
@HelaG : je n'ai pas de problème avec la version actuelle du graphe donc on peut clore cette issue.
