### ISSUE TITLE
Déplacer les règles dans un dépot

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/beta.gouv.fr#840]
> “toutes les règles contraignantes qui s’appliquent à tous les membres de l’incubateur sont déplacées dans un *dépôt*, qui fonctionne par le biais de RFC, c’est-à-dire avec de la revue obligatoire et plusieurs jours sans commentaires ; les _recommandations_, qui sont des bonnes pratiques non contraignantes, restent sur le wiki”

**Comment by MattiSG** [comment]
https://github.com/sgmap/regles
