### ISSUE TITLE
Mettre à jour la charte pour ajouter le sujet « bonjour »

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/beta.gouv.fr#842]
Amender la charte pour indiquer que c’est ok de dire bonjour d’une manière ou d’une autre tant que l’autre est ok, ou de ne pas dire bonjour si on n’en a pas envie ce jour-là, et que si on ne sait pas quoi faire on peut serrer la main.

La valeur par défaut devrait être “dire bonjour collectif à distance”.

**Comment by Morendil** [comment]
Tiens j'ai retrouvé un des articles qui m'a fait réfléchir sur ce sujet et je m'aperçois qu'il était de "notre" Romy: http://romy.tetue.net/arriver-en-retard-pour-eviter-la-bise

**Comment by Morendil** [comment]
Closed via https://github.com/sgmap/beta.gouv.fr/wiki/Charte/7c0f8e6f7aed414e98fd3b5a92d93aa4bde8187d
