### ISSUE TITLE
Ne pas répéter le titre des articles de blog

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#850]
Actuellement, le titre d'un article est dupliqué, une fois sur l'image d'illustration, une autre fois dans le corps du texte.

![capture d ecran 2017-07-21 a 15 00 23](https://user-images.githubusercontent.com/222463/28464405-57efad7a-6e25-11e7-847d-81329281d6d9.png)

**Comment by Flightan** [comment]
Si j'ai bien compris quand j'en ai parlé avec @Ismael-Hery, ce serait une bonne pratique.

**Comment by Ismael-Hery** [comment]
Hmm, je me rappelle pas trop de la conversation et de ce qui m'a poussé à te dire ça :-) N'empêche dans 1 article sur 2 le titre intégré à l'image est peu lisible alors que celui dans le texte l'est toujours et recueil sans doute plus de "vues d'oeil" ;-)

**Comment by MattiSG** [comment]
On peut envisager de diminuer encore l'intensité lumineuse de l'image de fond, mais la mise en page actuelle me perturbe à chaque fois (je relis deux fois pour être sûr que je n'ai pas loupé une différence).

**Comment by oncletom** [comment]
La duplication peut être gênante, je mesure mal l'impact négatif que ça peut avoir mais 2 remarques :

1. le titre gagnerait à être calé à gauche au même niveau que le texte, pour l'accompagner
2. le titre dans le bandeau gagnerait à être moins isolé du contenu (notamment par la date) pour conserver l'affordance entre titre et contenu, et éviter d'avoir recours à son doublement "au cas où"

Suggestion imagée :

![image](https://user-images.githubusercontent.com/138627/29310036-20dd930a-81a4-11e7-845d-7fdbdc28d42a.png)
