### ISSUE TITLE
Ajoute un email template pour les débutant-e-s

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/beta.gouv.fr#856]
Avec @hussardnum on essaye de trouver un moyen d'embarquer des débutant-e-s comme une manière d'accroître la diversité. Un blog post est à l'écriture, et à terme on espère pouvoir matérialiser des offres d'emploi ouvertes aux débutant-e-s, cf. #825.

Pour que cela soit possible, nous vous proposons d'utiliser la variante d'email de réponse suivante, laquelle faudrait-il ajouter au wiki :

> 
> Bonjour [prénom],
> 
> Merci de votre candidature; nous avons pris note de votre parcours de formation et de votre intérêt pour l'incubateur.
> 
> Nous n'avons pas actuellement la capacité d'encadrement nécessaire pour accompagner des personnes effectuant une première expérience professionnelle dans le développement de services numériques.
> 
> Nous ne pourrons donc pas donner suite dans l'immédiat et nous le regrettons. Si vous le souhaitez, nous pouvons vous ajouter à notre liste de candidat·e·s et vous recontacter lors de prochaines ouvertures de poste. Dans ce cas, indiquez-nous à partir de quand vous pensez être disponible. Nous vous invitons aussi à suivre notre page Recrutement: https://beta.gouv.fr/recrutement , où nous mentionnerons explicitement les postes susceptibles d'accueillir des candidats pour une première expérience dans notre domaine.

Et expliciter qu'il faut ajouter lesdits profils sur la section « débutant-e-s » du CRM de suivi.

**Comment by MattiSG** [comment]
[Fait](https://github.com/sgmap/beta.gouv.fr/wiki/Réponses-aux-mails).
