### ISSUE TITLE
Add wiki entry to increase ppl going speaking at confs

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/beta.gouv.fr#858]
Proposition: on rédige sur le Wiki une déclaration de principe favorisant notre participation à des confs (@hussardnum je prends)

**Comment by Morendil** [comment]
Via https://github.com/sgmap/beta.gouv.fr/wiki/L'atelier-d'%C3%A9criture/c71c340919d70ec4529a2a17743ff950cc3e84f6
