### ISSUE TITLE
Migrer api.gouv.fr vers api.beta.gouv.fr

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#92]
@ThibautGery

**Comment by ThibautGery** [comment]
Pour moi api.gouv.fr a sa propre URL => api.gouv.fr :smile: 
J'ai loupé un truc ?

**Comment by MattiSG** [comment]
Pour tant qu'on n'est pas en prod dessus (i.e. pour remplacer `api.gouv2.fr`)  :wink:

**Comment by jdesboeufs** [comment]
Pas api.gouv.fr.beta.gouv.fr ? :D
Le jeu. 10 mars 2016 à 09:54, Matti Schneider <notifications@github.com> a
écrit :

**Comment by ThibautGery** [comment]
> 
  Don't feed the troll

Okay ça marche

**Comment by MattiSG** [comment]
> @jdesboeufs Regarde les aurores boréales et tais-toi  :stuck_out_tongue_closed_eyes:

**Comment by MattiSG** [comment]
poke @ThibautGery

**Comment by MattiSG** [comment]
@ThibautGery attend d'avoir un rôle Ansible pour automatiser la génération de la config Nginx des pages statiques hébergées ailleurs. ETA 29/03.

**Comment by ThibautGery** [comment]
Done : 
 * [http://api.beta.gouv.fr/](http://api.beta.gouv.fr/) : faut-il ajouter un certificat https ?
 * [http://api.gouv2.fr/](http://api.gouv2.fr/) : faut-il ajouter un certificat https ?
 * [http://api.gouv.fr/](http://api.gouv.fr/) : protégé avec https et du basic auth

**Comment by MattiSG** [comment]
Top ! On peut dropper le `.gouv2`.
Du HTTPS sur `beta` serait pas mal, oui. Non bloquant ceci dit.

**Comment by ThibautGery** [comment]
Pour le certificat, il suffit que Jérôme les pose sur le serveur et je peux mettre à jour le script.

**Comment by MattiSG** [comment]
Peux-tu mettre à jour https://github.com/sgmap/beta.gouv.fr/tree/gh-pages/_startup stp ?
