### ISSUE TITLE
Migrer bourses vers bourse.beta.gouv.fr

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#93]

**Comment by ThibautGery** [comment]
C'est sur SRV1, donc manuel

**Comment by MattiSG** [comment]
https://bourse.beta.gouv.fr est en ligne, manque-t-il quelque chose ?

**Comment by MattiSG** [comment]
D'ailleurs, c'est `bourse` ou `bourses` ? Le domaine est `bourse`, mais le dépôt et le nom référencé sont `bourses`.

**Comment by MattiSG** [comment]
Closed via c481fadd5931d38fce3eaad96a58f3186ee12fa5
