### ISSUE TITLE
Migrer embauche vers embauche.beta.gouv.fr

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#94]
@laem

**Comment by jdesboeufs** [comment]
Alors ? :)

**Comment by MattiSG** [comment]
http://embauche.beta.gouv.fr semble accessible.
@laem 1. qu'est-ce qui bloque à la redirection de embauche.sgmap.fr ? 2. Peut-on passer en SSL ?

**Comment by laem** [comment]
Oui depuis vendredi. 
- J'ai une petite inquiétude sur le fichier [CNAME](https://github.com/sgmap/paie-www/blob/gh-pages/CNAME), qui est toujours sur embauche.sgmap.fr, mais ça semble marcher quand même. @MattiSG @jdesboeufs vous pouvez peut-être m'éclairer sur son utilité ?
- Je comptais migrer tous les services sur beta.gouv.fr avant de changer l'URL du site de présentation. Mais les deux sites peuvent co-exister un moment.

**Comment by MattiSG** [comment]
Le CNAME fait en sorte que les serveurs de GitHub gèrent [directement](https://help.github.com/articles/setting-up-your-pages-site-repository/) une requête lorsque tu configures les DNS de ton nom de domaine pour pointer vers chez eux. Si tu sers actuellement sur beta.gouv via `proxy_pass` tu n'en as pas besoin, mais il serait plus performant d'utiliser un CNAME.

**Comment by laem** [comment]
OK c'est bien comme ça pour le CNAME alors. 
Je passe actuellement les services en HTTPS :tada:

**Comment by jdesboeufs** [comment]
Le CNAME n'a pas d'intérêt dans le cas de la configuration actuelle ;)
Pour les performances, rien de grave. Et si vraiment ça devient gênant on a plein de parades qui existent.

**Comment by MattiSG** [comment]
Remplacer l'adresse de contact par contact@embauche.beta.gouv.fr (j'ai créé les redirections et redirigé embauche@sgmap.fr)

**Comment by laem** [comment]
:+1: bien vu et merci !
