### ISSUE TITLE
Migrer OpenAcademie vers openacademie.beta.gouv.fr

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#98]
@Ismael-Hery

**Comment by Ismael-Hery** [comment]
Ok je vois avec Eytan.

**Comment by eytan55** [comment]
Je m'en charge, quel est la procédure?

**Comment by MattiSG** [comment]
À définir  :wink: 
Ça dépend de la manière dont l'applicatif est hébergé actuellement. Vois avec la personne qui t'a aidé à déployer sur `sgmap.fr`.

**Comment by eytan55** [comment]
Peut tu être plus précis? déployer sur sgmap.fr?

**Comment by MattiSG** [comment]
OpenAcademie est actuellement déployé sur `openacademie.sgmap.fr`. Il faut donc suivre la même « procédure » pour déployer sur `openacademie.beta.gouv.fr`, procédure qui dépend a priori de ton environnement et de ton applicatif.

**Comment by Ismael-Hery** [comment]
OpenAcademie c'est du "gh-pages" sur github.

**Comment by MattiSG** [comment]
Avec de l'offloading via `proxy_pass` du coup ? Cool, on a déjà un exemple avec ça alors  :)

@eytan55 tu sais écrire une config Nginx basique ?

**Comment by eytan55** [comment]
Non , je ne sais pas faire cela :(

Le 10 mars 2016 à 14:26, Matti Schneider <notifications@github.com> a écrit
:

**Comment by eytan55** [comment]
Re,
Que puis-je faire pour faire avancer les choses?

**Comment by MattiSG** [comment]
Merci @eytan55 de relancer sur ce sujet. Voir avec @ThibautGery et/ou @jdesboeufs si OpenAcademie est géré par l'hyperviseur, auquel cas dépendance sur #92, ou si c'est géré par une conf Nginx sur `srv1` à mettre à jour.

Tu peux surtout d'ores et déjà identifier si une procédure de migration plus compliquée qu'une 301 doit être mise en place.

**Comment by ThibautGery** [comment]
La redirection est pas sur srv2, mais je pense qu'elle y a toute sa place sachant qu'on voudrait (à terme) vider srv1. Pour mettre ça sur srv2 il faut : 
 * rediriger le dns avec un cname vers srv2
 * générer le certificat ssl (poke @jdesboeufs)
 * crypter le certificat
 * ajouter trois lignes de conf (poke gla)

**Comment by jdesboeufs** [comment]
Configuration déployée sur `srv1`, sur le même modèle que `beta.gouv.fr`.
Je me sens pas de déployer via l'hyperviseur sans Thibaut (que je ne ping pas car il est en vacances).

**Comment by eytan55** [comment]
Done!

Accessible depuis https://openacademie.beta.gouv.fr/

**Comment by MattiSG** [comment]
Génial, merci !

**Comment by MattiSG** [comment]
@eytan55 peux-tu mettre à jour la description de la startup sur beta.gouv.fr stp ?  :)

https://github.com/sgmap/beta.gouv.fr/tree/gh-pages/_startup

**Comment by eytan55** [comment]
Fait :)

**Comment by Ismael-Hery** [comment]
@eytan55 : peux tu prevenir tous les partenaires de Open Academie avec
Pierre de Maulmont ? Possible de mettre une redirection HTTP ou un message
sur l'ancienne adresse ?

Le lundi 21 mars 2016, eytan55 <notifications@github.com> a écrit :

> Fait :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sgmap/beta.gouv.fr/issues/98#issuecomment-199301720>
>


-- 
Ismaël Héry
+ 33 6 12 88 02 15

**Comment by jdesboeufs** [comment]
Il y a une redirection 301 sur l'ancienne adresse.
Modulo ton cache DNS ;)
