### ISSUE TITLE
Migrer Retraite vers retraite.beta.gouv.fr

### ISSUE THREAD

**Issue by MattiSG** [sgmap/beta.gouv.fr#99]
@xnopre

**Comment by ThibautGery** [comment]
Done: 
 * [https://retraite.beta.gouv.fr](https://retraite.beta.gouv.fr)  
 * [https://recette-retraite.beta.gouv.fr](https://recette-retraite.beta.gouv.fr)

Par contre j'ai pas forcé l'utilisation de HTTPS (c'est juste une option a ajouter: `force_ssl: true` [ici](https://gogs.sgmap.fr/infra/hypervisor/src/master/group_vars/hypervisors#L97))

**Comment by ThibautGery** [comment]
Redirection vers HTTPS OK => il faut mettre une 301 à partir des anciennes URL vers les nouvelles

**Comment by xnopre** [comment]
@ThibautGery pas indispensable (la redirection pour les anciennes URLs), j'informerai les utilisateurs et on pourra supprimer les anciennes :-)

**Comment by MattiSG** [comment]
:dancer: Merci @ThibautGery !!!!

**Comment by MattiSG** [comment]
@xnopre peux-tu mettre à jour la description de la startup sur beta.gouv.fr stp ?  :)

**Comment by xnopre** [comment]
@MattiSG je pense que c'est bon
