### ISSUE TITLE
Visualiser le site en local avec ruby < 2

### ISSUE THREAD

**Issue by pblayo** [sgmap/beta.gouv.fr#997]
La procédure indiquée dans CONTRIBUTING.md ne fonctionne pas lorsque la version de ruby est inférieur ou égale à 1.9 :

    beta.gouv.fr$ bundle install
    [...]
    public_suffix-2.0.5 requires ruby version >= 2.0, which is incompatible with the current version, ruby 1.9.3p484

Pour résoudre ce problème, j'ai écrit un Dockerfile.

**Comment by Morendil** [comment]
Pourquoi as-tu besoin impérativement de Ruby 1.9 ?

L'architecture de ce dépôt incarne une volonté historique de suivre les versions référencées sur https://pages.github.com/versions/ afin de se rapprocher le plus possible de la prod. Si tu es curieux tu peux notamment regarder notre Gemfile très non-standard.

Il me semble par ailleurs que quitte à dockerizer le truc tu gagnerais à le faire avec une image contenant un Ruby plus récent, d'où ma question ci-dessus. Dans ce cas tu peux aussi jeter un oeil à https://github.com/Morendil/github-pages-docker et https://hub.docker.com/r/morendil/github-pages/ (un peu out of date).

L'usage de Docker au sein du sous-ensemble des membres de l'incubateur qui codent sur beta.gouv.fr (le site) est resté assez marginal (je pense être le seul), je serais ravi qu'on en discute pour améliorer l'expérience des utilisateurs de Docker.

**Comment by pblayo** [comment]
@Morendil : si tu maintient déjà à jour une image docker, bien sur il vaut mieux que je l'utilise. Je le mentionnerais dans CONTRIBUTING.md  (c'était assez décevant que la procédure d'install ne fonctionne pas).

Je suis étonné que tu soit le seul à utiliser docker mais il doit y avoir des éléments de contexte qui me manque. Une mauvaise expérience de docker dans le passé ?

> Pourquoi as-tu besoin impérativement de Ruby 1.9 ?

Je n'ai pas besoin de ruby 1.9, c'est que je ne peux pas générer le site car ma machine a une version de ruby inférieur à 2 : oj (une dépendance de jsonlint) doit être compilé et çà ne marche qu'avec ruby 2 ou supérieur.

> suivre les versions référencées sur https://pages.github.com/versions/

L'idée de ce Dockerfile c'était justement de suivre les versions référencées par github.
Le `bundle install` lancé au démarrage de docker se fonde sur le Gemfile dont tu parles.

```
Install missing gems with `bundle install`
```

Donc au pris d'une génération à chaque relance du serveur jekyll les versions devraient être toujours alignées. Une image nécessite d'être régénérée à chaque changement de dépendance (ou alors j'ai raté quelque chose).

**Comment by Morendil** [comment]
Au temps pour moi, j'ai enfin compris: tu veux utiliser Docker *pour exécuter le site avec une version récente de Ruby*, pas pour l'utiliser avec la 1.9.

J'ai déjà soumis une PR avec un Dockerfile, cette PR a été fermée non mergée par souci de ne pas augmenter la complexité du dépôt et parce que j'en aurais été le seul usager. Cela dit, nous nous donnons aussi la possibilité de revisiter périodiquement des décisions passées - prendre une décision à un instant t n'indique pas forcément que cette décision est éternellement la seule bonne option.

Le fait que l'install ne fonctionne pas en 1.9 serait une indication de la valeur qu'aurait un Dockerfile; il servirait de documentation (exécutable) des dépendances au niveau système. Mais il est de ce point de vue redondant avec le Gemfile, puisque ce dernier spécifie la version de Ruby (indirectement, en référençant les versions courantes de Github Pages).

Ma motivation pour utiliser Docker est la même que la tienne, isoler les environnements de dév de ma machine, par exemple pour ne pas avoir à savoir comment on met à jour Ruby sur Mac... Mais d'autres collègues pensent que Docker "résout" ce problème au prix d'une couche de complexité supplémentaire (et c'est bien le cas) et qu'il est aussi simple prendre le temps d'installer sur sa machine locale la version qui correspond à la prod du produit qu'ils développent.

**Comment by pblayo** [comment]
Le mieux sera qu'on en discute de vive voix :

> redondant avec le Gemfile

Je croyais au contraire que c'était ce Gemfile que `bundle install` utilisait au lancement du conteneur Docker. Je me trompe ?

> une couche de complexité supplémentaire

Le Dockerfile que je propose fait 2 lignes :
```
FROM jekyll/jekyll
RUN apk --update --no-cache add make
```

- la première référence l'image Docker officielle de jekyll
- il faut aussi make (seconde ligne) pour compiler `oj` tiré par `jslint`

Sur l'aspect couche : gérer une installation locale de ruby (différente de celle de la distrib) rajoute également une couche d'indirection par l'intermédiaire du PATH et des variables d'environnement .
